const questoes = [
    ["Qual é a principal função da administração segundo Henri Fayol?", "Prever, organizar, comandar, coordenar e controlar", "Planejar, executar, revisar e avaliar", "Dirigir, vender, controlar e comunicar", "Organizar, vender, investir e lucrar"],
    ["Qual das opções abaixo é uma função administrativa?", "Planejamento", "Vendas", "Produção", "Marketing"],
    ["O que representa a sigla SWOT?", "Forças, Fraquezas, Oportunidades e Ameaças", "Sucesso, Will, Organização e Tática", "Serviço, Will, Organização e Técnica", "Sistema, Workflow, Ordem e Trabalho"],
    ["Qual é a finalidade do planejamento estratégico?", "Definir os objetivos e metas de longo prazo", "Realizar o controle de qualidade", "Reduzir os custos operacionais", "Aumentar o número de funcionários"],
    ["Qual dos autores é considerado o pai da administração científica?", "Frederick Taylor", "Henri Fayol", "Max Weber", "Peter Drucker"],
    ["Qual é a estrutura mais comum em empresas tradicionais?", "Hierárquica", "Matricial", "Circular", "Horizontal"],
    ["O que caracteriza uma liderança democrática?", "O líder toma decisões com participação do grupo", "O líder toma todas as decisões sozinho", "O líder é ausente e deixa o grupo agir por conta própria", "O líder controla todos os processos sem diálogo"],
    ["O que é organograma?", "Representação gráfica da estrutura organizacional", "Tabela de horários de trabalho", "Lista de funcionários", "Resumo das metas da empresa"],
    ["Qual é o foco da administração de recursos humanos?", "Gerenciar o capital humano da organização", "Vender produtos aos clientes", "Aumentar o lucro com publicidade", "Cuidar das finanças da empresa"],
    ["O que é benchmarking?", "Comparar práticas da empresa com as de concorrentes", "Contratar novos funcionários", "Treinar líderes internos", "Reduzir custos com tecnologia"],
    ["Qual é o objetivo da administração por objetivos (APO)?", "Alinhar metas individuais com os objetivos da empresa", "Focar apenas nos lucros", "Melhorar o clima organizacional", "Eliminar os processos burocráticos"],
    ["Em uma empresa, o que significa a sigla KPI?", "Indicador-chave de desempenho", "Índice de produção interna", "Informação para qualidade industrial", "Indicador para questões internas"],
    ["Qual é o conceito de cultura organizacional?", "Conjunto de valores, crenças e comportamentos da empresa", "Plano de marketing do setor", "Organização do ambiente físico da empresa", "Manual de segurança do trabalho"],
    ["Qual é uma vantagem da descentralização administrativa?", "Maior agilidade na tomada de decisões", "Controle total do gestor central", "Redução da comunicação interna", "Eliminação dos líderes intermediários"],
    ["O que é a análise de mercado?", "Estudo sobre consumidores, concorrentes e tendências", "Levantamento do patrimônio da empresa", "Relatório sobre despesas fixas", "Cálculo dos impostos anuais"],
    ["O que representa a sigla TQM?", "Gestão da Qualidade Total", "Tempo, Qualidade e Motivação", "Tecnologia de Qualidade Moderna", "Teoria Quantitativa de Mercado"],
    ["Qual o papel de um gerente de projetos?", "Planejar, executar e monitorar projetos", "Executar tarefas operacionais", "Administrar apenas a folha de pagamento", "Atuar como consultor externo"],
    ["A motivação no ambiente de trabalho é importante porque:", "Aumenta a produtividade e o engajamento dos colaboradores", "Reduz o número de produtos", "Evita o uso de tecnologias", "Controla os investimentos externos"],
    ["Qual é o principal objetivo da logística empresarial?", "Garantir que o produto certo chegue ao cliente certo, no tempo certo", "Criar novos produtos", "Gerenciar a equipe de vendas", "Controlar o orçamento do setor financeiro"],
    ["O que é o ciclo PDCA?", "Planejar, Executar, Verificar e Agir", "Produzir, Desenvolver, Calcular e Avaliar", "Planejamento, Desenvolvimento, Controle e Análise", "Programar, Distribuir, Corrigir e Agir"],
    ["O que caracteriza uma organização matricial?", "Combina estrutura funcional com estrutura por projetos", "É baseada apenas em tarefas rotineiras", "É dividida apenas por localização geográfica", "Não possui hierarquia definida"],
    ["Quem é Peter Drucker?", "Considerado o pai da administração moderna", "Criador da logística empresarial", "Fundador da Teoria X e Y", "Especialista em finanças pessoais"],
    ["O que é controle organizacional?", "Avaliação e correção das atividades para atingir os objetivos", "Supervisão física do ambiente de trabalho", "Controle de entrada e saída de funcionários", "Verificação de lucros mensais"],
    ["Quais são os níveis de planejamento organizacional?", "Estratégico, tático e operacional", "Superior, médio e baixo", "Inicial, médio e avançado", "Interno, externo e global"],
    ["O que é turnover?", "Taxa de rotatividade de funcionários", "Nível de engajamento da equipe", "Quantidade de produtos produzidos", "Índice de satisfação dos clientes"],
    ["Qual ferramenta é usada para analisar o ambiente interno e externo da empresa?", "Matriz SWOT", "Matriz BCG", "Matriz de Porter", "Fluxograma de processos"],
    ["Qual é uma das principais características do empreendedor?", "Capacidade de inovar e correr riscos", "Evitar mudanças", "Trabalhar apenas com segurança", "Seguir sempre os processos existentes"],
    ["O que é um plano de negócios?", "Documento que descreve os objetivos e estratégias de um negócio", "Relatório anual de lucros", "Lista de fornecedores", "Tabela de horários dos funcionários"],
    ["Qual é a função da controladoria?", "Dar suporte ao processo decisório por meio de informações contábeis e gerenciais", "Supervisionar a área de vendas", "Controlar o setor de compras", "Planejar ações de marketing"],
    ["A Teoria das Relações Humanas destacou a importância de:", "Fatores humanos e sociais no ambiente de trabalho", "Redução de custos com tecnologia", "Regras rígidas e controle máximo", "Divisão detalhada de tarefas"],
    ["Qual é o principal objetivo da gestão de pessoas?", "Desenvolver e manter talentos dentro da organização", "Reduzir custos operacionais", "Controlar a produção", "Aumentar o número de clientes"],
    ["O que é endomarketing?", "Marketing voltado para o público interno da empresa", "Marketing de produtos digitais", "Venda de produtos no exterior", "Análise do comportamento do consumidor"],
    ["Na matriz BCG, um produto com alta participação de mercado e alto crescimento é classificado como:", "Estrela", "Vaca leiteira", "Abacaxi", "Ponto de interrogação"],
    ["O que representa o conceito de 'Just in Time' na logística?", "Produzir e entregar apenas o necessário, no momento certo", "Estocar o máximo possível", "Distribuir sem controle de tempo", "Priorizar entregas internacionais"],
    ["Qual a função principal do fluxo de caixa?", "Controlar entradas e saídas de dinheiro da empresa", "Avaliar a satisfação do cliente", "Medir a produtividade dos funcionários", "Controlar a jornada de trabalho"],
    ["O que é análise SWOT utilizada no planejamento estratégico?", "Ferramenta para identificar forças, fraquezas, oportunidades e ameaças", "Planilha de controle financeiro", "Tabela de produtividade dos funcionários", "Plano de comunicação institucional"],
    ["Qual é o papel do feedback na gestão de pessoas?", "Ajudar no desenvolvimento e alinhamento de expectativas", "Reduzir custos com folha de pagamento", "Delegar tarefas administrativas", "Evitar reuniões de equipe"],
    ["O que é CRM?", "Gestão de relacionamento com o cliente", "Controle de riscos de mercado", "Recursos contábeis mensais", "Cadastro regional de marketing"],
    ["Qual é o principal objetivo do marketing de relacionamento?", "Fidelizar clientes a longo prazo", "Aumentar os preços dos produtos", "Divulgar apenas em redes sociais", "Expandir para outros países"],
    ["A logística reversa está relacionada a:", "Retorno de produtos do consumidor ao fabricante", "Reposição de mercadorias nos pontos de venda", "Planejamento da entrega de insumos", "Processos de transporte aéreo"],
    ["Qual é o principal objetivo do orçamento empresarial?", "Planejar e controlar os recursos financeiros", "Contratar fornecedores internacionais", "Criar estratégias de marketing", "Controlar a entrada de novos funcionários"],
    ["O que é job rotation?", "Rodízio de funções para desenvolver habilidades diversas", "Promoção automática de cargos", "Demissão por performance", "Formação técnica obrigatória"],
    ["No marketing, o que é o conceito de 'mix de marketing'?", "Conjunto de variáveis controláveis: produto, preço, praça e promoção", "Lista de produtos disponíveis", "Campanhas digitais mensais", "Avaliação de produtos semestrais"],
    ["Qual é uma das vantagens da terceirização?", "Foco da empresa em atividades principais", "Redução da carga horária", "Aumento do número de departamentos", "Expansão da estrutura física"],
    ["O que significa ROI?", "Retorno sobre o investimento", "Registro de operações internas", "Regime de orientação institucional", "Relatório orçamentário individual"],
    ["Qual é o papel de um analista financeiro?", "Analisar dados e propor estratégias para saúde financeira da empresa", "Administrar a equipe de vendas", "Executar tarefas de marketing", "Recrutar colaboradores"],
    ["Qual é a função do capital de giro?", "Manter a empresa operando no curto prazo", "Investir em imóveis", "Pagar dividendos aos acionistas", "Contratar novos executivos"],
    ["O que é plano de cargos e salários?", "Sistema que define funções e respectivas remunerações", "Lista de funcionários e datas de admissão", "Tabela com o número de demissões", "Orçamento de publicidade mensal"],
    ["Em logística, o que significa lead time?", "Tempo total entre o pedido e a entrega", "Período de férias dos colaboradores", "Data de validade dos produtos", "Tempo de estudo do consumidor"],
    ["Qual é o papel da controladoria na empresa?", "Monitorar e avaliar os resultados financeiros e operacionais", "Gerenciar campanhas de marketing", "Definir metas de RH", "Controlar os horários de entrada"],
    ["O que é planejamento tático?", "Tradução do plano estratégico em ações para departamentos", "Execução de tarefas operacionais", "Definição da missão da empresa", "Definição de metas para o CEO"],
    ["Qual é a diferença entre missão e visão?", "Missão define o propósito atual, visão é o objetivo futuro", "Missão é financeira, visão é operacional", "Missão é interna, visão é externa", "Não há diferença significativa"],
    ["O que é turnover voluntário?", "Saída do funcionário por decisão própria", "Demissão por justa causa", "Promoção interna", "Transferência de setor"],
    ["O que significa PEPS na área de custos?", "Primeiro a entrar, primeiro a sair", "Produto especial por semana", "Programa de excelência pessoal", "Projeto estratégico para sucesso"],
    ["Qual é a importância da curva ABC?", "Classificar produtos ou clientes de acordo com sua relevância", "Distribuir prêmios para os melhores funcionários", "Organizar arquivos contábeis", "Ordenar os setores por ordem alfabética"],
    ["O que é análise de desempenho?", "Avaliação periódica de resultados e competências dos colaboradores", "Pesquisa de clima organizacional", "Controle de estoque semanal", "Verificação do faturamento anual"],
    ["Qual é o papel da liderança situacional?", "Adaptar o estilo de liderança conforme o perfil e maturidade da equipe", "Ser sempre autoritário", "Ignorar a opinião dos subordinados", "Manter o mesmo estilo de gestão"],
    ["Qual a principal característica da administração pública?", "Foco no bem coletivo e na legalidade", "Maximização do lucro", "Atendimento exclusivo a clientes VIPs", "Ações de marketing intensas"],
    ["O que é clima organizacional?", "Ambiente psicológico e social dentro da empresa", "Temperatura do ambiente de trabalho", "Decoração da empresa", "Layout do escritório"],
    ["No contexto de inovação, o que é startup?", "Empresa emergente com modelo de negócio escalável", "Franquia tradicional", "Multinacional consolidada", "Empresa sem fins lucrativos"],
    ["Qual é o foco do planejamento estratégico?", "Definir os objetivos de longo prazo da organização", "Controlar despesas mensais", "Recrutar novos funcionários", "Organizar reuniões semanais"],
    ["O que significa benchmarking?", "Comparar práticas da empresa com as de outras organizações", "Controlar o ponto eletrônico", "Revisar documentos fiscais", "Distribuir lucros entre os sócios"],
    ["Na administração, o que representa o organograma?", "Representação gráfica da estrutura organizacional", "Relatório de desempenho anual", "Fluxo de caixa semanal", "Agenda de reuniões da diretoria"],
    ["Qual a principal característica de uma liderança democrática?", "Envolve a equipe nas decisões", "Centraliza todas as decisões", "Evita qualquer tipo de feedback", "Foca apenas no lucro"],
    ["O que é planejamento operacional?", "Detalhamento das ações de curto prazo", "Definição de missão e visão", "Estudo de mercado internacional", "Análise de concorrência"],
    ["A análise PESTEL avalia fatores:", "Políticos, econômicos, sociais, tecnológicos, ecológicos e legais", "Pessoais e emocionais", "Educacionais e científicos", "Financeiros e contábeis"],
    ["Qual o principal papel do gerente de projetos?", "Garantir a entrega de um projeto dentro do prazo, custo e escopo definidos", "Elaborar estratégias de marketing", "Liderar reuniões de RH", "Organizar o estoque"],
    ["O que representa o conceito de cultura organizacional?", "Conjunto de valores, crenças e práticas compartilhadas por uma empresa", "Tipo de produto vendido", "Layout da empresa", "Horário de funcionamento"],
    ["O que é capital fixo?", "Bens duráveis usados no processo produtivo", "Valores em caixa", "Lucros não distribuídos", "Contas a receber do mês"],
    ["Qual é o papel do setor de compras?", "Adquirir materiais e serviços necessários para o funcionamento da empresa", "Vender produtos aos clientes", "Emitir folhas de pagamento", "Controlar redes sociais"],
    ["O que significa taxa de absenteísmo?", "Índice de faltas dos colaboradores", "Custo com novos equipamentos", "Lucro líquido anual", "Volume de vendas mensais"],
    ["Qual é o objetivo do marketing digital?", "Promover produtos ou marcas por meio de canais online", "Imprimir panfletos", "Organizar feiras presenciais", "Controlar estoque físico"],
    ["O que é liderança autocrática?", "Estilo de liderança centralizado, com pouca participação da equipe", "Participação ativa dos colaboradores", "Rotatividade de chefia", "Foco na motivação individual"],
    ["O que é um KPI?", "Indicador-chave de desempenho", "Plano de contingência", "Sistema contábil", "Ferramenta de comunicação"],
    ["Qual é o principal objetivo da análise de viabilidade?", "Avaliar se um projeto ou investimento é financeiramente e tecnicamente possível", "Contratar novos estagiários", "Desenvolver um plano de marketing", "Organizar campanhas internas"],
    ["No contexto administrativo, o que é compliance?", "Conformidade com leis, normas e regulamentos", "Relatório de produtividade", "Treinamento de vendas", "Planejamento de férias"],
    ["O que é turnover?", "Rotatividade de funcionários", "Crescimento da receita", "Aumento da produção", "Capacitação de colaboradores"],
    ["Qual é a função da análise de riscos?", "Identificar e mitigar potenciais ameaças aos objetivos da empresa", "Organizar o fluxo de caixa", "Criar campanhas publicitárias", "Contratar novos fornecedores"],
    ["O que representa o lucro líquido?", "Receita total menos todas as despesas", "Valor de vendas sem impostos", "Faturamento bruto", "Descontos concedidos"],
    ["Qual é a principal função de um business plan?", "Estruturar uma ideia de negócio com projeções e estratégias", "Relatar gastos operacionais", "Descrever o plano de cargos", "Planejar a rotina do RH"],
    ["O que significa análise horizontal nas finanças?", "Comparação de valores financeiros ao longo de períodos", "Distribuição de custos por setor", "Avaliação de clientes inadimplentes", "Projeção de estoque futuro"],
    ["O que é o ponto de equilíbrio em uma empresa?", "Momento em que receitas igualam as despesas", "Total de vendas mensais", "Valor ideal de investimento", "Quantidade de funcionários"],
    ["O que é liderança transformacional?", "Inspira e motiva os colaboradores a desenvolverem seu potencial", "Foca apenas em metas", "Não realiza feedbacks", "Evita mudanças"],
    ["O que são stakeholders?", "Pessoas ou grupos interessados nas decisões e resultados de uma organização", "Investidores estrangeiros", "Funcionários da contabilidade", "Clientes externos apenas"],
    ["O que significa controle orçamentário?", "Comparar o planejado com o realizado financeiramente", "Emitir boletos bancários", "Contratar fornecedores", "Reduzir pessoal"],
    ["Qual a importância do inventário?", "Controlar e registrar todos os bens e mercadorias da empresa", "Verificar produtividade dos funcionários", "Divulgar metas trimestrais", "Acompanhar a movimentação bancária"],
    ["O que é uma franquia?", "Modelo de negócio replicado com autorização do franqueador", "Sociedade limitada", "Cooperativa de crédito", "Empresa estatal"],
    ["Qual o foco da análise de mercado?", "Entender o comportamento do consumidor e da concorrência", "Identificar talentos internos", "Reduzir a carga tributária", "Recrutar novos líderes"],
    ["O que é custo fixo?", "Despesas que não variam com o volume de produção", "Compra de matéria-prima", "Comissão de vendas", "Descontos promocionais"],
    ["O que significa taxa de conversão no marketing digital?", "Percentual de visitantes que realizam uma ação desejada", "Valor médio de compra", "Tempo de navegação no site", "Total de acessos mensais"],
    ["O que significa a sigla SWOT na análise estratégica?", "Forças, Fraquezas, Oportunidades e Ameaças", "Soluções, Valores, Operações e Táticas", "Sistemas, Workflows, Objetivos e Técnicas", "Serviços, Willpower, Organização e Treinamento"],
  ["Qual é o principal objetivo do planejamento tático?", "Traduzir objetivos estratégicos em planos de médio prazo", "Definir a missão da empresa", "Avaliar concorrentes diretos", "Organizar tarefas operacionais diárias"],
  ["O que caracteriza uma organização matricial?", "Combina estruturas funcionais e por projetos", "Tem apenas uma linha de comando", "É voltada exclusivamente para produção", "Funciona de forma informal"],
  ["O que representa o conceito de missão em uma empresa?", "Razão de existir da organização", "Projeção financeira para o ano", "Descrição do portfólio de produtos", "Análise de concorrência"],
  ["O que é controle de qualidade?", "Conjunto de ações para garantir que produtos ou serviços atendam aos padrões", "Controle de ponto eletrônico", "Gestão de equipe de vendas", "Definição de metas de marketing"],
  ["Qual a função do capital de giro?", "Manter as operações diárias da empresa funcionando", "Comprar imóveis comerciais", "Pagar lucros aos acionistas", "Aplicar em renda fixa"],
  ["O que é uma análise de custo-benefício?", "Avaliação entre os custos envolvidos e os benefícios esperados de uma ação", "Controle de gastos com fornecedores", "Auditoria de processos", "Cálculo de margem de lucro"],
  ["Qual a principal função da contabilidade gerencial?", "Ajudar na tomada de decisão interna", "Registrar notas fiscais", "Emitir guias de impostos", "Arquivar documentos legais"],
  ["Qual é o significado de missão, visão e valores?", "Elementos que orientam o propósito, metas futuras e princípios da organização", "Nomes de cargos da diretoria", "Tipos de orçamento", "Documentos obrigatórios da empresa"],
  ["O que significa endomarketing?", "Marketing voltado para o público interno da organização", "Promoções nas redes sociais", "Campanhas publicitárias externas", "Treinamento de fornecedores"],
  ["O que é análise de concorrência?", "Estudo das forças e fraquezas dos concorrentes do mercado", "Revisão de contratos", "Gestão de tributos", "Avaliação de satisfação interna"],
  ["O que é a curva ABC?", "Classificação de itens com base em sua importância financeira", "Método de cálculo de juros", "Modelo de recrutamento", "Ferramenta de marketing digital"],
  ["Qual o papel do departamento de Recursos Humanos?", "Gerir pessoas e promover o desenvolvimento organizacional", "Controlar entradas de mercadoria", "Planejar campanhas de venda", "Emitir notas fiscais"],
  ["O que significa a sigla ERP?", "Sistema Integrado de Gestão Empresarial", "Estudo de Risco de Produção", "Equipe de Resultados Positivos", "Estrutura de Responsabilidade Produtiva"],
  ["Qual é o objetivo da avaliação de desempenho?", "Medir a performance de colaboradores em relação a metas", "Analisar concorrentes", "Registrar ponto dos funcionários", "Criar campanhas de vendas"],
  ["O que representa o planejamento financeiro?", "Organização e previsão dos recursos monetários de uma empresa", "Controle de estoque", "Criação de identidade visual", "Elaboração de contratos"],
  ["O que é coaching empresarial?", "Processo de desenvolvimento de habilidades profissionais", "Treinamento técnico de máquinas", "Controle de custos operacionais", "Consultoria contábil"],
  ["Qual é o objetivo do marketing de relacionamento?", "Fidelizar clientes através de experiências e comunicação contínua", "Anunciar em redes sociais", "Distribuir brindes", "Reduzir custos de venda"],
  ["O que é o planejamento de carreira?", "Estratégia para desenvolvimento profissional dentro da empresa", "Revisão de folha de pagamento", "Elaboração de currículo", "Organização de eventos"],
  ["O que significa feedback?", "Retorno dado a uma pessoa sobre seu desempenho", "Relatório de vendas", "Balanço financeiro", "Controle de estoque"],
  ["Qual é a principal função do ciclo PDCA?", "Melhoria contínua de processos", "Aumentar o lucro imediato", "Reduzir o número de funcionários", "Organizar eventos empresariais"],
  ["O que caracteriza uma liderança situacional?", "Adapta o estilo de liderança conforme o contexto", "Segue sempre o mesmo padrão", "Evita dar ordens", "Foca apenas em resultados"],
  ["Qual é a importância da comunicação interna?", "Melhora o fluxo de informações e o clima organizacional", "Substitui o setor de vendas", "Elimina reuniões", "Evita avaliação de desempenho"],
  ["O que é job rotation?", "Rodízio de funções entre os colaboradores para ampliar conhecimentos", "Aumento de salário por tempo de casa", "Treinamento de novos fornecedores", "Desligamento em massa"],
  ["Qual é o objetivo da logística reversa?", "Gerenciar o retorno de produtos ou resíduos ao ciclo produtivo", "Organizar a entrega de pedidos", "Controlar a frota da empresa", "Reduzir o uso de embalagens"],
  ["O que significa outsourcing?", "Terceirização de serviços ou processos", "Promoção interna de funcionários", "Criação de um novo departamento", "Substituição de equipamentos antigos"],
  ["O que é uma startup?", "Empresa emergente com modelo de negócio inovador e escalável", "Empresa pública", "Filial de multinacional", "Loja de grande porte"],
  ["Qual é o conceito de governança corporativa?", "Conjunto de práticas para melhorar a gestão e a transparência das empresas", "Criação de novos cargos", "Revisão de contratos", "Análise de clientes"],
  ["O que é ciclo de vida do produto?", "Fases pelas quais um produto passa desde o lançamento até a retirada do mercado", "Período de férias coletivas", "Tempo de produção em fábrica", "Prazo de garantia do produto"],
  ["O que representa o índice de liquidez corrente?", "Capacidade da empresa em pagar suas dívidas de curto prazo", "Total de investimentos realizados", "Número de funcionários ativos", "Taxa de crescimento anual"],
  ["O que é benchmarking?", "Processo de comparar práticas da empresa com as de concorrentes ou líderes de mercado", "Compra de ações de concorrentes", "Avaliação de currículo de candidatos", "Auditoria financeira interna"],
  ["Qual o papel do plano de negócios?", "Guiar a criação e desenvolvimento de uma empresa", "Contratar novos funcionários", "Monitorar redes sociais", "Organizar a folha de pagamento"],
  ["O que é um KPI (Key Performance Indicator)?", "Indicador-chave de desempenho", "Plano de contratação", "Método de auditoria", "Ferramenta de vendas diretas"],
  ["Qual a principal função da controladoria?", "Fornecer informações para o processo decisório por meio de análises financeiras e operacionais", "Gerir o marketing da empresa", "Contratar novos fornecedores", "Planejar eventos corporativos"],
  ["O que é turnover?", "Índice de rotatividade de funcionários", "Aumento do capital social", "Reajuste salarial anual", "Crescimento de vendas"],
  ["A gestão por competências busca:", "Alinhar as habilidades dos colaboradores com as necessidades estratégicas da empresa", "Reduzir custos com treinamento", "Evitar promoções internas", "Descentralizar a liderança"],
  ["O que significa PEPS na administração de estoques?", "Primeiro a Entrar, Primeiro a Sair", "Pedido Especial Para Saída", "Produto em Estoque Para Saída", "Ponto Estratégico Para Serviço"],
  ["O que é análise SWOT utilizada para?", "Avaliar cenários internos e externos de uma organização", "Organizar reuniões internas", "Controlar entradas e saídas de caixa", "Planejar eventos corporativos"],
  ["A motivação no ambiente de trabalho é importante para:", "Aumentar o engajamento e a produtividade", "Reduzir o horário de trabalho", "Eliminar cargos redundantes", "Substituir equipamentos antigos"],
  ["O que é a teoria da hierarquia das necessidades de Maslow?", "Modelo que classifica as necessidades humanas em diferentes níveis", "Estrutura de cargos em uma empresa", "Método de auditoria interna", "Sistema de avaliação de fornecedores"],
  ["A análise PESTEL estuda:", "Fatores políticos, econômicos, sociais, tecnológicos, ecológicos e legais que afetam a empresa", "Indicadores de produtividade", "Mapeamento de clientes", "Sistema de comissões"],
  ["Qual o objetivo da análise de viabilidade econômica?", "Verificar se um projeto é financeiramente sustentável", "Reduzir o número de colaboradores", "Criar campanhas de marketing", "Identificar falhas em sistemas"],
  ["O que caracteriza a liderança transformacional?", "Capacidade de inspirar e motivar mudanças significativas", "Foco exclusivo em metas", "Estilo autoritário", "Delegação completa sem supervisão"],
  ["O que é controle orçamentário?", "Monitoramento das receitas e despesas previstas e realizadas", "Gestão de benefícios dos funcionários", "Controle de ponto eletrônico", "Gerenciamento da comunicação externa"],
  ["O que significa CRM (Customer Relationship Management)?", "Gestão do relacionamento com o cliente", "Sistema de pagamento online", "Controle de riscos de mercado", "Relatório de produtividade"],
  ["O que é estratégia empresarial?", "Conjunto de ações planejadas para alcançar os objetivos da organização", "Campanhas de redes sociais", "Promoções de produtos", "Feiras e eventos corporativos"],
  ["Qual o papel da cultura organizacional?", "Influenciar comportamentos e decisões dentro da empresa", "Definir salários", "Planejar férias coletivas", "Controlar a entrada de visitantes"],
  ["O que é uma análise de mercado?", "Estudo detalhado do setor, concorrência e consumidores", "Avaliação de currículos", "Estudo interno da contabilidade", "Pesquisa de satisfação de fornecedores"],
  ["O que significa B2B?", "Negócios realizados entre empresas", "Compra de produtos online", "Marketing de relacionamento com clientes", "Promoções para consumidores finais"],
  ["O que é planejamento estratégico?", "Definição de metas e caminhos para o futuro da organização", "Controle de estoque", "Gestão de conflitos", "Administração da folha de pagamento"],
  ["O que representa o conceito de tomada de decisão?", "Processo de escolher a melhor alternativa entre várias opções", "Delegar tarefas operacionais", "Aplicar pesquisas com clientes", "Registrar balanços financeiros"],
  ["O que são metas SMART?", "Metas específicas, mensuráveis, atingíveis, relevantes e com prazo definido", "Planos de marketing digital", "Indicadores de clima organizacional", "Ferramentas de CRM"],
  ["O que é o ponto de equilíbrio?", "Momento em que receitas se igualam aos custos", "Meta de vendas mensal", "Cálculo do salário médio", "Nível de satisfação do cliente"],
  ["O que é um organograma?", "Representação gráfica da estrutura hierárquica de uma empresa", "Planejamento de turnos", "Lista de fornecedores", "Fluxo de caixa"],
  ["A análise de DRE (Demonstração do Resultado do Exercício) permite:", "Avaliar o lucro ou prejuízo de um período", "Medir a satisfação do cliente", "Definir metas de RH", "Criar campanhas de email"],
  ["Qual a principal finalidade do orçamento empresarial?", "Planejar e controlar os recursos financeiros", "Calcular férias dos funcionários", "Emitir notas fiscais", "Registrar patentes"],
  ["O que é a técnica 5W2H?", "Ferramenta para definição e execução de planos de ação", "Relatório de avaliação financeira", "Modelo de plano de marketing", "Método de auditoria de processos"],
  ["O que caracteriza a liderança democrática?", "Estímulo à participação e ao diálogo na tomada de decisões", "Controle total das ações pelos líderes", "Delegação sem supervisão", "Indiferença com os subordinados"],
  ["O que é capital fixo?", "Investimentos em bens duráveis usados na produção", "Dinheiro em caixa", "Lucro líquido", "Impostos a pagar"],
  ["O que é custo variável?", "Despesa que varia conforme a produção ou vendas", "Despesa fixa mensal", "Salário do administrador", "Custo de aquisição de clientes"]
]

export default questoes