const questoes = [
    ["Qual das opções é uma função privativa do enfermeiro segundo a Lei nº 7.498/86?", "Prescrição da assistência de enfermagem", "Administração de medicamentos via oral", "Aferição da pressão arterial", "Coleta de exames laboratoriais"],
    ["Qual o principal objetivo do Protocolo de Manchester na triagem?", "Classificar a gravidade do paciente para definir o tempo de espera", "Agilizar o atendimento médico independente do caso", "Evitar internações hospitalares desnecessárias", "Priorizar pacientes por ordem de chegada"],
    ["O que significa o termo 'asepsia'?", "Ausência de micro-organismos patogênicos", "Presença controlada de fungos", "Remoção mecânica de sujeira", "Limpeza com sabão comum"],
    ["Qual equipamento é essencial para administração segura de soro intravenoso?", "Bomba de infusão", "Oxímetro de pulso", "Desfibrilador", "Aspirador cirúrgico"],
    ["Em qual situação o enfermeiro deve fazer Notificação Compulsória?", "Suspeita de dengue", "Consulta de rotina", "Dor lombar crônica", "Febre ocasional"],
    ["Quanto tempo deve durar a lavagem correta das mãos?", "40 a 60 segundos", "10 a 15 segundos", "Mais de 2 minutos", "30 segundos"],
    ["Qual a posição recomendada para administração de enema?", "Decúbito lateral esquerdo", "Fowler", "Decúbito dorsal", "Trendelemburg"],
    ["O que é anúria?", "Ausência completa de urina", "Urina com sangue", "Diminuição do volume urinário", "Aumento da frequência urinária"],
    ["Qual tipo de isolamento é indicado para tuberculose pulmonar ativa?", "Isolamento respiratório", "Isolamento de contato", "Isolamento protetor", "Isolamento entérico"],
    ["Durante passagem de sonda nasogástrica, o que indica posicionamento incorreto nos pulmões?", "Tosse persistente", "Dilatação abdominal", "Náuseas", "Ausência de peristaltismo"],
    ["Qual é o principal objetivo da Sistematização da Assistência de Enfermagem (SAE)?", "Organizar o trabalho profissional com base no método científico", "Controlar a agenda dos profissionais", "Reduzir custos com medicamentos", "Agilizar consultas médicas"],
    ["O que significa o termo 'iatrogênico'?", "Dano causado por ação médica ou de enfermagem", "Doença hereditária", "Infecção comunitária", "Agente imunológico"],
    ["Qual a finalidade do uso de EPI (Equipamento de Proteção Individual)?", "Proteger o profissional contra riscos ocupacionais", "Reduzir custos hospitalares", "Evitar a fadiga durante o plantão", "Melhorar a comunicação com pacientes"],
    ["A punção venosa periférica é realizada com qual finalidade?", "Administração de medicamentos e coleta de sangue", "Verificação de glicemia", "Ausculta cardíaca", "Verificação de sinais neurológicos"],
    ["Qual é a via de administração mais rápida para medicamentos?", "Intravenosa", "Oral", "Intramuscular", "Subcutânea"],
    ["Em qual posição o paciente deve ficar para punção lombar?", "Decúbito lateral com flexão máxima", "Fowler", "Trendelemburg", "Decúbito ventral"],
    ["Qual dos sinais vitais indica uma frequência cardíaca elevada?", "Taquicardia", "Bradicardia", "Hipotermia", "Dispneia"],
    ["O que é gasometria arterial?", "Exame que avalia o equilíbrio ácido-básico e gases no sangue", "Teste de função renal", "Avaliação de coagulação", "Verificação da glicose no sangue"],
    ["A escala de Glasgow é utilizada para avaliar:", "Nível de consciência", "Estado nutricional", "Risco de queda", "Capacidade respiratória"],
    ["O que é um curativo oclusivo?", "Curativo que impede a entrada de ar e líquidos", "Curativo com uso exclusivo de gaze", "Curativo apenas com esparadrapo", "Curativo usado apenas em queimaduras"],
    ["O que caracteriza uma ferida contaminada?", "Presença de micro-organismos sem sinais de infecção", "Ferida com necrose extensa", "Ferida com sangramento ativo", "Ferida limpa e fechada"],
    ["Qual a importância do balanço hídrico?", "Avaliar a entrada e saída de líquidos no organismo", "Controlar o peso do paciente", "Medir a temperatura corporal", "Verificar o nível de oxigênio no sangue"],
    ["O uso da técnica de escuta ativa é importante para:", "Melhorar a comunicação e o acolhimento ao paciente", "Reduzir o tempo de consulta", "Controlar a agenda do setor", "Evitar conflitos entre profissionais"],
    ["Qual é o principal objetivo da enfermagem em cuidados paliativos?", "Promover conforto e qualidade de vida", "Realizar procedimentos invasivos", "Manter o paciente acordado", "Administrar antibióticos de forma contínua"],
    ["A coloração azulada da pele indica:", "Cianose", "Icterícia", "Palidez", "Hiperemia"],
    ["O que significa SVO?", "Serviço de Verificação de Óbitos", "Sistema de Vigilância Ocupacional", "Sonda Vesical de Oxigênio", "Suporte Ventilatório Otimizado"],
    ["Qual a conduta correta após acidente com material perfurocortante?", "Lavar o local e comunicar imediatamente o setor responsável", "Cobrir com gaze e seguir o plantão", "Aplicar álcool e seguir para casa", "Esperar sintomas aparecerem"],
    ["Na passagem da sonda vesical, é necessário utilizar qual técnica?", "Técnica asséptica", "Técnica de escuta ativa", "Técnica de contenção", "Técnica de escarificação"],
    ["O que é um paciente com risco de broncoaspiração?", "Aquele com dificuldade de deglutição ou inconsciência", "Aquele com febre alta", "Aquele com feridas abertas", "Aquele em uso de antibióticos"],
    ["A temperatura axilar considerada febre é a partir de:", "37,8°C", "36,5°C", "37,0°C", "38,5°C"],
    ["Qual é o valor normal da frequência respiratória em adultos?", "12 a 20 incursões por minuto", "20 a 30 incursões por minuto", "8 a 12 incursões por minuto", "30 a 40 incursões por minuto"],
    ["A escara por pressão é causada principalmente por:", "Imobilidade prolongada", "Infecção hospitalar", "Alimentação inadequada", "Uso excessivo de analgésicos"],
    ["A higiene das mãos deve ser realizada por quanto tempo, segundo a OMS?", "Pelo menos 40 a 60 segundos", "20 segundos", "15 segundos", "Mais de 2 minutos"],
    ["Qual a melhor via de administração para medicamentos irritantes?", "Intramuscular profunda", "Oral", "Subcutânea", "Intradérmica"],
    ["A administração de oxigênio exige prescrição?", "Sim, é considerado medicamento", "Não, é um cuidado básico", "Apenas em hospitais", "Apenas para pacientes em ventilação"],
    ["A Sonda de Levine é utilizada para:", "Drenagem ou alimentação gástrica", "Oxigenação", "Coleta de urina", "Controle de glicemia"],
    ["O termo 'anóxia' refere-se a:", "Ausência de oxigênio nos tecidos", "Excesso de glicose no sangue", "Diminuição do potássio", "Inflamação pulmonar"],
    ["A técnica correta de verificação de pulso radial envolve:", "Palpar com os dedos indicador e médio", "Usar o polegar para sentir o pulso", "Contar por 10 segundos e multiplicar por 6", "Auscultar com estetoscópio"],
    ["Qual destas doenças exige isolamento por gotículas?", "Tuberculose", "COVID-19", "Hepatite C", "HIV"],
    ["Qual é a função principal do esfigmomanômetro?", "Medir a pressão arterial", "Avaliar a saturação de oxigênio", "Verificar a glicemia", "Controlar o débito urinário"],
    ["A administração de insulina é geralmente feita por via:", "Subcutânea", "Intravenosa", "Oral", "Intramuscular"],
    ["O uso de calçados fechados e antiderrapantes é uma recomendação de segurança para:", "Prevenir acidentes ocupacionais", "Melhorar o conforto", "Evitar resfriados", "Manter postura correta"],
    ["Qual a principal complicação da hipoglicemia grave não tratada?", "Perda de consciência e morte", "Febre alta", "Aumento da pressão arterial", "Formigamento nos pés"],
    ["A infecção do trato urinário é mais comum em pacientes com:", "Sonda vesical de demora", "Dieta rica em proteínas", "Uso de antibióticos", "Atividade física intensa"],
    ["O termo 'asepsia' significa:", "Ausência de micro-organismos", "Presença controlada de vírus", "Isolamento parcial", "Uso de máscara cirúrgica"],
    ["O curativo com hidrocolóide é indicado para:", "Feridas com exsudato leve a moderado", "Feridas secas", "Feridas necrosadas com odor", "Feridas com sangramento ativo"],
    ["Qual é o nome da técnica usada para auscultar sons intestinais?", "Ausculta abdominal", "Percussão digestiva", "Palpação gástrica", "Inspeção colônica"],
    ["A via intradérmica é usada com frequência em:", "Testes de alergia", "Administração de analgésicos", "Hidratação venosa", "Aplicação de insulina"],
    ["O termo 'letargia' se refere a:", "Estado de sonolência e lentidão", "Agitação extrema", "Febre persistente", "Alterações cardíacas"],
    ["A anotação de enfermagem deve ser feita com:", "Objetividade e clareza", "Opiniões pessoais", "Siglas incomuns", "Linguagem informal"],
    ["Qual é a principal função dos glóbulos vermelhos?", "Transportar oxigênio", "Produzir hormônios", "Combater infecções", "Formar coágulos"],
    ["A punção venosa periférica deve ser realizada preferencialmente em:", "Veias dos membros superiores", "Veias do pescoço", "Veias femorais", "Veias do dorso do pé"],
    ["Qual é a posição indicada para administração de enemas?", "Decúbito lateral esquerdo", "Decúbito dorsal", "Fowler", "Trendelemburg"],
    ["A escala de Glasgow é usada para avaliar:", "Nível de consciência", "Pressão arterial", "Capacidade respiratória", "Dor torácica"],
    ["Qual é a função da insulina?", "Reduzir a glicose no sangue", "Aumentar a pressão arterial", "Estimular o apetite", "Regular o sono"],
    ["A melhor maneira de prevenir trombose venosa profunda em pacientes acamados é:", "Mobilização precoce", "Administração de analgésicos", "Hidratação oral", "Uso de meias comuns"],
    ["O uso de luvas é obrigatório em:", "Qualquer contato com fluidos corporais", "Administração de medicamentos orais", "Consulta de rotina", "Aferição de sinais vitais"],
    ["Em caso de queimadura de 2º grau, deve-se:", "Cobrir com compressa estéril e procurar atendimento", "Aplicar gelo diretamente", "Estourar bolhas", "Passar manteiga ou pasta de dente"],
    ["Qual o objetivo da lavagem gástrica?", "Remover substâncias tóxicas do estômago", "Estimular a digestão", "Aumentar a produção de suco gástrico", "Tratar constipação"],
    ["A vacinação contra hepatite B deve ser feita em:", "3 doses", "1 dose", "2 doses", "4 doses"],
    ["O que é um sinal de sepse?", "Febre, taquicardia e confusão mental", "Letargia e bradicardia", "Apetite aumentado e rubor facial", "Pressão arterial normal"],
    ["O cateter de Foley é usado para:", "Drenagem urinária", "Infusão de soro", "Aspirar secreções pulmonares", "Administração de alimentos"],
    ["A escala de dor mais utilizada na enfermagem é:", "Escala numérica de 0 a 10", "Escala de Braden", "Escala de Coma de Glasgow", "Escala de Norton"],
    ["A ausculta pulmonar com presença de estertores pode indicar:", "Presença de secreções nos pulmões", "Hiperglicemia", "Isquemia cerebral", "Febre alta"],
    ["O tempo de preenchimento capilar normal é de até:", "2 segundos", "5 segundos", "1 segundo", "4 segundos"],
    ["Qual o local mais indicado para aplicação de heparina subcutânea?", "Abdômen", "Glúteo", "Coxa", "Braço"],
    ["A hemoglobina baixa pode indicar:", "Anemia", "Hipertensão", "Infecção viral", "Desidratação"],
    ["Na técnica asséptica, o campo estéril deve ser mantido a:", "Altura da cintura", "Altura dos pés", "Qualquer altura", "Acima da cabeça"],
    ["O uso de protetor solar é uma recomendação para:", "Prevenção de câncer de pele", "Controle de pressão arterial", "Tratamento da acne", "Redução do colesterol"],
    ["Um dos sinais precoces de hipovolemia é:", "Taquicardia", "Hiperglicemia", "Bradicardia", "Eritema"],
    ["O que caracteriza uma ferida infectada?", "Presença de pus, odor fétido e calor local", "Dor intensa sem sinais visíveis", "Apenas sangramento ativo", "Edema sem coloração"],
    ["Qual é a finalidade da técnica de Fowler?", "Melhorar a expansão pulmonar", "Reduzir a pressão intracraniana", "Aumentar a circulação periférica", "Facilitar a digestão"],
    ["A administração de medicamentos por via intramuscular deve ser feita em ângulo de:", "90 graus", "45 graus", "15 graus", "120 graus"],
    ["O tempo ideal para lavagem das mãos, segundo a ANVISA, é de pelo menos:", "40 a 60 segundos", "10 segundos", "30 segundos", "1 minuto e 30 segundos"],
    ["A coloração ictérica da pele está relacionada ao aumento de:", "Bilirrubina", "Hemoglobina", "Creatinina", "Glicose"],
    ["A pressão arterial é considerada normal quando está próxima de:", "120x80 mmHg", "100x60 mmHg", "140x90 mmHg", "130x100 mmHg"],
    ["O soro fisiológico 0,9% é considerado:", "Isotônico", "Hipotônico", "Hipertônico", "Glicosado"],
    ["O cateter nasal é indicado para administração de:", "Oxigênio", "Soro fisiológico", "Anestésico", "Medicação intravenosa"],
    ["A temperatura corporal normal em adultos varia entre:", "36°C a 37,5°C", "35°C a 36°C", "37,5°C a 39°C", "34°C a 35°C"],
    ["Qual exame detecta infecção urinária?", "EAS (exame de urina tipo I)", "Eletrocardiograma", "Hemograma completo", "Exame de escarro"],
    ["A profilaxia é um conjunto de medidas para:", "Prevenir doenças", "Curar doenças crônicas", "Tratar sintomas", "Estabilizar fraturas"],
    ["A ausculta cardíaca deve ser feita com o paciente em:", "Decúbito dorsal", "Posição fetal", "Trendelemburg", "Decúbito lateral direito"],
    ["Qual é a principal complicação da hiperglicemia não tratada?", "Cetoacidose diabética", "Hipotermia", "Isquemia renal", "Artrite reumatoide"],
    ["A dieta branda é indicada para pacientes com:", "Distúrbios gastrointestinais", "Hipoglicemia", "Fraturas ósseas", "Alergias respiratórias"],
    ["O curativo oclusivo é utilizado principalmente para:", "Manter a ferida protegida da umidade", "Estimular sangramento", "Reduzir edema", "Absorver secreção em excesso"],
    ["Qual é o objetivo da oxigenoterapia?", "Corrigir a hipoxemia", "Aumentar a frequência cardíaca", "Diminuir o tônus muscular", "Prevenir convulsões"],
    ["A administração de medicamentos subcutâneos ocorre geralmente no:", "Tecido adiposo", "Músculo esquelético", "Vaso sanguíneo", "Epiderme"],
    ["O que é um abscesso?", "Acúmulo de pus em cavidade fechada", "Inflamação generalizada", "Formação de coágulos", "Ferida aberta com sangramento ativo"],
    ["O oxímetro de pulso mede:", "Saturação de oxigênio e frequência cardíaca", "Temperatura e frequência respiratória", "Glicemia capilar", "Pressão venosa central"],
    ["Qual é o local mais seguro para aplicação de injeção intramuscular em adultos?", "Região ventroglútea", "Região deltoide", "Região dorsal", "Região occipital"],
    ["O que significa o termo 'anúria'?", "Ausência total de produção de urina", "Aumento da frequência urinária", "Dor ao urinar", "Presença de sangue na urina"],
    ["A escara de decúbito é causada principalmente por:", "Pressão prolongada sobre a pele", "Infecção bacteriana", "Desidratação", "Excesso de movimento"],
    ["Qual é a finalidade do uso de luvas estéreis?", "Evitar contaminação durante procedimentos invasivos", "Manter as mãos aquecidas", "Prevenir suor nas mãos", "Reduzir o uso de álcool em gel"],
    ["Qual desses sinais vitais é considerado o quinto sinal vital?", "Dor", "Temperatura", "Frequência respiratória", "Pressão arterial"],
    ["A punção venosa periférica é geralmente realizada para:", "Administração de medicamentos ou coleta de sangue", "Verificar pressão intracraniana", "Realizar biópsia", "Imobilizar fraturas"],
    ["O que é uma via enteral de administração de medicamentos?", "Por meio do trato gastrointestinal", "Por injeção subcutânea", "Por via respiratória", "Por aplicação tópica"],
    ["A lavagem gástrica é indicada em casos de:", "Intoxicação por ingestão de substâncias", "Hipotermia", "Hipoglicemia", "Desidratação grave"],
    ["O que caracteriza a febre?", "Temperatura acima de 37,8°C", "Temperatura abaixo de 35°C", "Saturação de oxigênio acima de 98%", "Frequência cardíaca de 60 bpm"],
    ["Em qual posição o paciente deve estar para inserção de sonda nasogástrica?", "Fowler (cabeceira elevada)", "Decúbito lateral", "Trendelemburg", "Genupeitoral"],
    ["O sinal de Battelle está relacionado a:", "Presença de líquido no abdômen", "Infecção respiratória", "Retenção urinária", "Aumento da frequência cardíaca"],
    ["O termo 'cianose' refere-se a:", "Coloração azulada da pele por falta de oxigênio", "Presença de hematomas", "Ressecamento da pele", "Aumento da temperatura corporal"],
    ["Qual exame é utilizado para verificar a glicemia capilar?", "Teste com glicosímetro", "Eletrocardiograma", "Ultrassonografia", "Eletroencefalograma"],
    ["Quando ocorre a hipovolemia?", "Quando há perda excessiva de líquidos", "Quando há excesso de sangue nos vasos", "Quando o sódio está elevado", "Quando há aumento da pressão intracraniana"],
    ["O que é um colar cervical?", "Dispositivo para imobilizar o pescoço", "Faixa de contenção abdominal", "Meia compressora para varizes", "Aparelho ortodôntico"],
    ["A ausculta pulmonar com presença de estertores pode indicar:", "Acúmulo de secreção nos pulmões", "Infarto agudo do miocárdio", "Infecção urinária", "Problemas hepáticos"],
    ["Em um curativo úmido, o objetivo é:", "Manter a umidade ideal para cicatrização", "Secar completamente a ferida", "Bloquear a entrada de oxigênio", "Estimular sangramento"],
    ["A escala de Glasgow é utilizada para avaliar:", "Nível de consciência", "Pressão arterial", "Força muscular", "Temperatura corporal"],
    ["A profilaxia com anticoagulantes visa evitar:", "Formação de trombos", "Infecção viral", "Alergia a medicamentos", "Dor crônica"],
    ["O que é parenteral?", "Via de administração fora do trato digestivo", "Via oral", "Via respiratória", "Via ocular"],
    ["A ventilação mecânica é indicada para pacientes com:", "Insuficiência respiratória grave", "Febre persistente", "Glicemia alterada", "Problemas dermatológicos"],
    ["Qual o objetivo da antissepsia da pele antes de um procedimento invasivo?", "Reduzir a carga microbiana da área", "Lubrificar a pele", "Aumentar a circulação sanguínea", "Diminuir a sensibilidade local"],
    ["A administração de medicamentos por via IM significa:", "Intramuscular", "Intramedular", "Intrameninge", "Intramamária"],
    ["O uso da cânula de Guedel é indicado para:", "Manter a via aérea pérvia em pacientes inconscientes", "Aumentar a pressão arterial", "Realizar drenagem de abscesso", "Facilitar a alimentação enteral"],
    ["O que é um abscesso?", "Acúmulo de pus em um tecido", "Tumor benigno", "Lesão vascular", "Gânglio linfático aumentado"],
    ["A técnica correta para aferição da pressão arterial inclui:", "Utilizar estetoscópio e esfigmomanômetro", "Medir com termômetro digital", "Verificar através do oxímetro", "Palpar a temperatura da pele"],
    ["Em pacientes acamados, a mudança de decúbito deve ser feita a cada:", "2 horas", "4 horas", "6 horas", "1 hora"],
    ["O que é gasometria arterial?", "Exame que avalia gases sanguíneos", "Avaliação do ritmo respiratório", "Medição da pressão intracraniana", "Verificação de função hepática"],
    ["Qual é o valor normal da saturação de oxigênio (SpO₂)?", "Acima de 95%", "Abaixo de 85%", "Entre 70% e 80%", "Exatamente 90%"],
    ["A SNG (sonda nasogástrica) pode ser usada para:", "Administração de dieta e medicação", "Aplicação de colírios", "Exames laboratoriais", "Coleta de secreção vaginal"],
    ["O que é a técnica de escovação cirúrgica?", "Lavagem minuciosa das mãos e antebraços para cirurgia", "Escovação dos dentes antes do plantão", "Limpeza de materiais contaminados", "Higienização do leito hospitalar"],
    ["A conduta adequada para evitar lesões por pressão inclui:", "Mudança de decúbito e hidratação da pele", "Reduzir alimentação", "Imobilizar o paciente constantemente", "Manter o paciente com cobertores pesados"],
    ["A via subcutânea é usada para aplicar medicamentos como:", "Insulina", "Anestésico geral", "Soro glicosado", "Colírio"],
    ["A temperatura corporal normal varia entre:", "36°C e 37,5°C", "35°C e 36°C", "37,5°C e 39°C", "38°C e 40°C"],
    ["O que são cuidados paliativos?", "Cuidados focados na qualidade de vida do paciente terminal", "Ações de prevenção de acidentes", "Treinamento físico em UTI", "Uso de medicamentos experimentais"],
    ["O uso prolongado de sonda vesical pode causar:", "Infecção urinária", "Melhora na função renal", "Aumento da pressão arterial", "Redução da micção"],
    ["O pulso radial é comumente aferido no:", "Punho", "Pescoço", "Tornozelo", "Peito"],
    ["O que caracteriza a diarreia?", "Evacuação líquida frequente", "Prisão de ventre", "Presença de sangue nas fezes", "Diminuição da urina"],
    ["O que é um paciente em estado de choque?", "Paciente com perfusão inadequada dos tecidos", "Paciente muito agitado", "Paciente com hipoglicemia leve", "Paciente em repouso absoluto"],
    ["A biossegurança em enfermagem é importante para:", "Proteger o profissional e o paciente de riscos biológicos", "Evitar perda de tempo com EPIs", "Promover marketing hospitalar", "Eliminar burocracias legais"],
    ["Qual é a finalidade da heparina em ambientes hospitalares?", "Prevenir tromboses", "Reduzir dores musculares", "Aumentar apetite", "Tratar infecções virais"]
    ["Qual a finalidade da lavagem gástrica?", "Remover conteúdo tóxico do estômago", "Estimular o apetite", "Promover digestão acelerada", "Reduzir a acidez gástrica"],
    ["O uso de luvas é obrigatório em procedimentos que envolvem:", "Contato com fluidos corporais", "Conversas com o paciente", "Atividades administrativas", "Medidas antropométricas"],
    ["O que significa o termo 'asepsia'?", "Ausência de micro-organismos patogênicos", "Limpeza com água e sabão", "Técnica de esterilização por calor", "Eliminação de pragas hospitalares"],
    ["A hipoglicemia pode causar:", "Confusão mental e desmaios", "Pressão arterial elevada", "Hipertermia", "Aumento da diurese"],
    ["A punção venosa periférica é realizada para:", "Administração de medicamentos e coleta de sangue", "Medir frequência cardíaca", "Verificar temperatura", "Observar reflexos motores"],
    ["A avaliação do nível de consciência pode ser feita através da escala:", "Glasgow", "Richmond", "Bristol", "Barthel"],
    ["A pressão arterial ideal em um adulto saudável é em torno de:", "120/80 mmHg", "150/100 mmHg", "90/60 mmHg", "140/90 mmHg"],
    ["A oxigenoterapia é indicada para pacientes com:", "Hipoxemia", "Hipertensão", "Febre", "Dores articulares"],
    ["O edema é caracterizado por:", "Acúmulo anormal de líquido nos tecidos", "Redução da massa muscular", "Rigidez articular", "Elevação da pressão arterial"],
    ["A temperatura retal tende a ser:", "Mais alta que a axilar", "Igual à bucal", "Menor que a temperatura ambiente", "Idêntica à temperatura da pele"],
    ["O curativo oclusivo tem como função:", "Isolar a ferida de agentes externos", "Manter a ferida seca", "Evitar cicatrização", "Estimular sangramento local"],
    ["A saturação de oxigênio abaixo de 90% indica:", "Hipoxemia", "Hipertensão", "Hipertermia", "Bradicardia"],
    ["A administração por via endovenosa permite:", "Ação rápida do medicamento", "Maior absorção gástrica", "Redução da dor local", "Evitar contato com o sangue"],
    ["O que deve ser feito antes da administração de qualquer medicamento?", "Conferir os 5 certos (paciente, medicamento, dose, horário e via)", "Avisar o acompanhante", "Solicitar jejum de 8 horas", "Medir a temperatura corporal"],
    ["A presença de escaras em pacientes acamados indica:", "Falta de mudança de decúbito", "Infecção pulmonar", "Desnutrição grave", "Uso excessivo de medicamentos"],
    ["A ausculta pulmonar é feita com:", "Estetoscópio", "Termômetro", "Esfigmomanômetro", "Oximetria digital"],
    ["A profilaxia é uma medida para:", "Prevenir doenças", "Tratar doenças", "Curar infecções", "Reduzir temperatura corporal"],
    ["O cateter de Foley é utilizado para:", "Drenagem urinária contínua", "Coleta de secreção brônquica", "Administração de dieta enteral", "Aspiração gástrica"],
    ["A via tópica de administração de medicamentos é aquela:", "Aplicada sobre a pele ou mucosas", "Injetada no músculo", "Introduzida por via retal", "Diluída em solução salina"],
    ["A desinfecção de materiais visa:", "Eliminar a maioria dos micro-organismos", "Esterilizar completamente os objetos", "Remover sujidade visível", "Evitar quebra de equipamentos"]
    ["Qual o objetivo principal da técnica de higiene das mãos?", "Reduzir a transmissão de micro-organismos", "Aumentar a circulação sanguínea", "Prevenir desidratação", "Estimular o apetite"],
    ["A febre é considerada quando a temperatura corporal está acima de:", "37,8°C", "36,5°C", "36,0°C", "38,5°C"],
    ["O pulso carotídeo é localizado:", "No pescoço", "No punho", "Na perna", "No dorso da mão"],
    ["O banho no leito é indicado para:", "Pacientes com mobilidade reduzida", "Todos os pacientes", "Pessoas com feridas abertas", "Pacientes com febre"],
    ["O uso de EPI (Equipamento de Proteção Individual) visa:", "Proteger o profissional e o paciente", "Reduzir custos hospitalares", "Facilitar a comunicação", "Aumentar a produtividade"],
    ["A via subcutânea de administração de medicamentos é usada principalmente para:", "Insulina", "Antibióticos", "Soro fisiológico", "Vitaminas"],
    ["A função principal da veia é:", "Levar o sangue ao coração", "Bombear sangue", "Oxigenar os tecidos", "Realizar trocas gasosas"],
    ["A frequência respiratória normal em adultos é de:", "12 a 20 rpm", "5 a 10 rpm", "20 a 30 rpm", "25 a 35 rpm"],
    ["A escala de Braden é usada para:", "Avaliar risco de úlceras por pressão", "Medir nível de dor", "Identificar déficit nutricional", "Aferir o nível de glicose"],
    ["Um sinal comum de desidratação é:", "Mucosas ressecadas", "Febre alta", "Hiperatividade", "Bradicardia"],
    ["O esfigmomanômetro é utilizado para:", "Medir a pressão arterial", "Avaliar saturação", "Aferir temperatura", "Administrar medicamentos"],
    ["O colar cervical é um dispositivo usado para:", "Imobilizar a coluna cervical", "Evitar quedas", "Reduzir febre", "Prevenir edema"],
    ["O sistema tegumentar é formado por:", "Pele, unhas e pelos", "Ossos e músculos", "Vasos sanguíneos", "Glândulas endócrinas"],
    ["A troca de curativo deve ser feita com técnica:", "Asséptica", "Simples", "Estética", "Empírica"],
    ["A ausculta cardíaca é realizada com o estetoscópio posicionado sobre:", "O precórdio", "O pescoço", "A lombar", "O braço"],
    ["Qual é a posição mais indicada para realizar a lavagem intestinal?", "Decúbito lateral esquerdo", "Decúbito dorsal", "Fowler", "Trendelemburg"],
    ["A administração de medicamentos por via intramuscular exige o uso de:", "Agulha longa", "Agulha curta", "Cateter", "Conta-gotas"],
    ["O paciente com nível de consciência rebaixado corre risco de:", "Aspiração pulmonar", "Hiperatividade", "Hipertermia", "Hipotrofia"],
    ["A prevenção de quedas em ambientes hospitalares pode incluir:", "Uso de grades laterais na cama", "Luzes apagadas durante a noite", "Tapetes escorregadios", "Calçados sem antiderrapante"],
    ["A glicemia capilar é um exame usado para:", "Avaliar o nível de açúcar no sangue", "Medir a frequência cardíaca", "Detectar infecções urinárias", "Avaliar capacidade pulmonar"] 

];

export default questoes;