const questoes = [
    ["Qual o valor máximo da Escala de Coma de Glasgow?", "15", "10", "12", "20"],
    ["Qual o valor mínimo que pode ser atribuído na Escala de Coma de Glasgow?", "3", "0", "1", "5"],
    ["A Escala de Coma de Glasgow avalia principalmente:", "A resposta neurológica", "A capacidade respiratória", "A pressão arterial", "O nível de dor"],
    ["A Escala de Coma de Glasgow é dividida em quantos parâmetros?", "3", "2", "4", "5"],
    ["Quais são os três parâmetros avaliados pela Escala de Coma de Glasgow?", "Abertura ocular, resposta verbal e resposta motora", "Frequência cardíaca, motricidade e fala", "Reflexo pupilar, fala e movimentos", "Sensibilidade, fala e orientação"],
    ["Na abertura ocular, qual a pontuação para resposta espontânea?", "4", "3", "2", "1"],
    ["Na resposta verbal, qual pontuação é atribuída a uma conversa orientada?", "5", "4", "3", "6"],
    ["Na resposta motora, obedecer comandos verbais equivale a quantos pontos?", "6", "5", "4", "3"],
    ["Se o paciente abre os olhos apenas ao estímulo doloroso, qual a pontuação?", "2", "3", "1", "4"],
    ["Uma resposta verbal incompreensível recebe quantos pontos?", "2", "3", "4", "1"],
    ["Qual a pontuação de um paciente que não apresenta nenhuma resposta nos três parâmetros da escala?", "3", "0", "5", "6"],
    ["A Escala de Coma de Glasgow é especialmente útil em casos de:", "Traumatismo cranioencefálico", "Infecção urinária", "Insuficiência cardíaca", "Hipotermia"],
    ["Um paciente que responde a estímulos verbais, com frases confusas e retira o braço à dor tem uma pontuação de:", "10", "13", "8", "12"],
    ["Pontuações entre 13 e 15 na escala indicam:", "Traumatismo leve", "Coma profundo", "Traumatismo moderado", "Inconsciência total"],
    ["Pontuações entre 9 e 12 na Glasgow indicam:", "Traumatismo moderado", "Traumatismo grave", "Coma leve", "Paciente inconsciente"],
    ["Qual pontuação indica um estado de coma grave?", "Menor ou igual a 8", "Entre 9 e 12", "Maior que 13", "Exatamente 10"],
    ["A escala pode ser utilizada em pacientes entubados?", "Sim, com adaptações", "Não, nunca", "Apenas em crianças", "Apenas fora do hospital"],
    ["Se um paciente abre os olhos ao som, fala de forma confusa e localiza a dor, qual a pontuação total?", "12", "13", "11", "10"],
    ["Na resposta motora, uma flexão anormal (decorticação) recebe quantos pontos?", "3", "2", "4", "5"],
    ["Um paciente com abertura ocular espontânea, fala confusa e resposta motora ao estímulo doloroso apresenta qual pontuação?", "10", "12", "9", "8"],
    ["Qual é o objetivo principal da Escala de Coma de Glasgow?", "Avaliar o nível de consciência", "Avaliar a frequência respiratória", "Determinar a pressão intracraniana", "Avaliar a saturação de oxigênio"],
    ["A resposta motora de 'extensão anormal (descerebração)' recebe quantos pontos?", "2", "3", "4", "5"],
    ["Quando um paciente apresenta 'nenhuma resposta motora', ele recebe quantos pontos nesse critério?", "1", "0", "2", "3"],
    ["O que significa uma pontuação total de 15 na Escala de Glasgow?", "Estado neurológico normal", "Coma leve", "Estado vegetativo", "Inconsciência moderada"],
    ["Qual é a resposta ocular com menor pontuação?", "Nenhuma resposta", "Resposta ao som", "Resposta à dor", "Resposta espontânea"],
    ["A resposta verbal 'palavras inapropriadas' recebe quantos pontos?", "3", "2", "4", "5"],
    ["Qual resposta motora corresponde a 5 pontos?", "Localiza a dor", "Obedece a comandos", "Flexão normal à dor", "Flexão anormal"],
    ["A Escala de Glasgow pode ser usada em crianças?", "Sim, com adaptações específicas", "Não", "Somente após os 12 anos", "Apenas em recém-nascidos"],
    ["Qual a pontuação total possível combinando os piores escores nos três critérios da Escala?", "3", "0", "5", "6"],
    ["Se o paciente apenas emite sons sem formar palavras, ele recebe quantos pontos na resposta verbal?", "2", "3", "1", "4"],
    ["A Escala de Coma de Glasgow foi desenvolvida originalmente em qual país?", "Reino Unido", "Estados Unidos", "França", "Alemanha"],
    ["Se um paciente tem abertura ocular ao som, fala palavras inapropriadas e flexão normal à dor, qual é a pontuação?", "10", "9", "11", "8"],
    ["A Escala de Coma de Glasgow é comumente utilizada por profissionais de:", "Enfermagem e medicina", "Nutrição", "Fisioterapia", "Farmácia"],
    ["A ausência de resposta ocular, verbal e motora é indicativo de:", "Coma profundo", "Sedação leve", "Estado de alerta", "Hipotermia"],
    ["Uma resposta motora de 'obedece a comandos' é considerada:", "Melhor resposta possível", "Resposta mínima", "Resposta mediana", "Resposta incompleta"],
    ["Qual é a melhor pontuação possível para resposta verbal?", "5", "6", "4", "3"],
    ["Paciente com olhos abertos espontaneamente, fala orientada e obedece comandos terá que pontuação total?", "15", "12", "14", "13"],
    ["A Escala de Glasgow pode ser usada para avaliar:", "Alterações neurológicas", "Funções renais", "Capacidade hepática", "Função endócrina"],
    ["Se o paciente responde com gemidos, qual escore deve ser atribuído na resposta verbal?", "2", "3", "4", "1"],
    ["A pontuação da Escala de Glasgow deve ser reavaliada com qual frequência em pacientes críticos?", "Conforme protocolo da unidade", "A cada 24 horas", "Somente ao dar entrada no hospital", "Uma vez por semana"],
    ["Quantos critérios são avaliados na Escala de Coma de Glasgow?", "Três", "Dois", "Quatro", "Cinco"],
    ["Qual é o critério que avalia se o paciente consegue abrir os olhos?", "Resposta ocular", "Resposta verbal", "Resposta motora", "Reflexo pupilar"],
    ["A resposta verbal ‘confuso, mas responde’ corresponde a quantos pontos?", "4", "3", "5", "2"],
    ["Paciente que abre os olhos ao estímulo doloroso, emite sons incompreensíveis e flexiona normalmente à dor terá qual pontuação?", "8", "7", "9", "10"],
    ["A menor pontuação possível na Escala de Glasgow é:", "3", "0", "1", "4"],
    ["Qual valor indica um coma profundo na Escala de Glasgow?", "Menor ou igual a 8", "Maior que 12", "Exatamente 10", "Entre 13 e 15"],
    ["Um paciente com resposta motora de extensão recebe quantos pontos nesse critério?", "2", "1", "3", "4"],
    ["A Escala de Glasgow é utilizada principalmente em casos de:", "Traumatismo cranioencefálico", "Infarto do miocárdio", "Fraturas expostas", "Insuficiência renal"],
    ["A ausência total de resposta verbal, ocular e motora é indicada pela pontuação:", "3", "0", "1", "4"],
    ["A resposta ocular ‘abre os olhos ao som’ vale quantos pontos?", "3", "2", "4", "1"],
    ["Qual resposta verbal é classificada com 1 ponto?", "Nenhuma resposta verbal", "Palavras inapropriadas", "Confuso", "Palavras inteligíveis"],
    ["O paciente que localiza a dor recebe quantos pontos na resposta motora?", "5", "4", "3", "6"],
    ["A Escala de Glasgow é considerada um exame de:", "Avaliação neurológica", "Avaliação cardíaca", "Exame laboratorial", "Exame ortopédico"],
    ["Com uma pontuação de 9 na Escala de Glasgow, o paciente é considerado:", "Em coma moderado", "Consciente", "Em coma profundo", "Sem alterações"],
    ["A Escala de Glasgow foi criada em que década?", "1970", "1960", "1980", "1990"],
    ["Qual pontuação corresponde a ‘resposta ocular espontânea’?", "4", "3", "2", "1"],
    ["Flexão anormal à dor é uma resposta motora que recebe quantos pontos?", "3", "2", "4", "5"],
    ["A resposta verbal orientada vale quantos pontos?", "5", "4", "3", "2"],
    ["Qual é o objetivo de aplicar a Escala de Glasgow repetidamente?", "Monitorar a evolução do nível de consciência", "Estimar o tempo de internação", "Prever infecção hospitalar", "Evitar o uso de sedativos"],
    ["A pontuação máxima na resposta motora é atribuída quando o paciente:", "Obedece a comandos", "Flexiona à dor", "Localiza a dor", "Estende os membros"],
    ["A pontuação mínima para indicar coma profundo é:", "8", "10", "9", "12"],
    ["Quando se utiliza estímulo doloroso e o paciente não responde, qual escore ocular é dado?", "1", "2", "3", "4"],
    ["Um paciente que emite sons sem sentido recebe quantos pontos na resposta verbal?", "2", "1", "3", "4"],
    ["Um paciente que não apresenta nenhum movimento recebe qual pontuação na resposta motora?", "1", "2", "3", "0"],
    ["Paciente que abre os olhos espontaneamente, emite palavras inapropriadas e localiza a dor, totaliza quantos pontos?", "12", "11", "10", "13"],
    ["A Escala de Glasgow pode ser usada em conjunto com qual outro parâmetro vital?", "Escala de pressão intracraniana", "Escala de Apgar", "Frequência cardíaca", "Temperatura corporal"],
    ["Se um paciente abre os olhos ao som, fala de forma confusa e flexiona normalmente à dor, qual sua pontuação total?", "10", "9", "8", "11"],
    ["A Escala de Coma de Glasgow pode ser usada em:", "Ambiente hospitalar e pré-hospitalar", "Apenas em UTI", "Somente em consultórios", "Exclusivamente por médicos"],
    ["Se o paciente apresenta fala orientada e espontânea, mas não abre os olhos, a pontuação parcial é:", "9", "8", "7", "6"],
    ["A Escala de Glasgow auxilia na decisão sobre:", "Necessidade de intubação", "Uso de antibióticos", "Remoção de curativos", "Prescrição de dieta enteral"],
    ["Qual pontuação total indica o melhor estado neurológico possível na Escala de Coma de Glasgow?", "15", "12", "10", "14"],
    ["Qual a menor pontuação possível em um paciente avaliado pela Escala de Coma de Glasgow?", "3", "0", "2", "4"],
    ["A Escala de Coma de Glasgow é composta por quais avaliações?", "Abertura ocular, resposta verbal e resposta motora", "Frequência cardíaca, fala e pressão", "Motricidade, temperatura e resposta pupilar", "Tônus muscular, reflexo e fala"],
    ["Uma resposta motora com flexão anormal recebe quantos pontos?", "3", "2", "4", "5"],
    ["A ausência total de resposta verbal equivale a quantos pontos?", "1", "0", "2", "3"],
    ["Quando o paciente abre os olhos em resposta à dor, qual pontuação recebe?", "2", "3", "1", "4"],
    ["Abertura ocular espontânea equivale a quantos pontos?", "4", "3", "2", "1"],
    ["Um paciente que emite palavras inapropriadas recebe quantos pontos na resposta verbal?", "3", "2", "4", "5"],
    ["A melhor resposta motora possível é classificada com quantos pontos?", "6", "5", "4", "3"],
    ["Qual valor indica resposta verbal confusa na Escala de Glasgow?", "4", "3", "2", "5"],
    ["Quando um paciente em coma profundo é avaliado, normalmente apresenta que pontuação total?", "3", "6", "8", "9"],
    ["Qual objetivo principal da Escala de Coma de Glasgow?", "Avaliar o nível de consciência", "Verificar a respiração", "Medir a pressão arterial", "Controlar a glicemia"],
    ["Abertura ocular ao estímulo verbal vale quantos pontos?", "3", "2", "4", "1"],
    ["Movimento de retirada frente à dor equivale a quantos pontos?", "4", "5", "3", "2"],
    ["Quais são as pontuações possíveis para a abertura ocular?", "1 a 4", "1 a 5", "0 a 4", "1 a 3"],
    ["O que significa uma pontuação de 8 na Escala de Glasgow?", "Coma moderado", "Consciência plena", "Coma profundo", "Paciente sonolento"],
    ["A ausência de resposta motora tem qual pontuação?", "1", "0", "2", "3"],
    ["Um paciente que emite sons incompreensíveis recebe quantos pontos na resposta verbal?", "2", "1", "3", "4"],
    ["A Escala de Coma de Glasgow é especialmente útil para pacientes com:", "Traumatismo cranioencefálico", "Hipotermia", "Febre alta", "Infarto do miocárdio"],
    ["Flexão anormal frente à dor é classificada como:", "Resposta motora 3", "Resposta motora 4", "Resposta motora 2", "Resposta motora 5"],
    ["Qual pontuação verbal representa uma fala orientada e coerente?", "5", "4", "3", "6"],
    ["Abertura ocular ao estímulo doloroso vale:", "2", "3", "1", "4"],
    ["A Escala de Glasgow foi desenvolvida para:", "Avaliar pacientes com alteração de consciência", "Medir dor em pacientes crônicos", "Verificar força muscular", "Avaliar respiração em casos de asma"],
    ["Resposta motora de extensão anormal recebe quantos pontos?", "2", "3", "1", "4"],
    ["O que indica uma pontuação de 9 na Escala de Glasgow?", "Comprometimento neurológico moderado", "Paciente orientado", "Coma profundo", "Paciente com fala normal"],
    ["Qual pontuação verbal recebe um paciente sem resposta alguma?", "1", "2", "0", "3"],
    ["Quais são os valores possíveis para a resposta motora?", "1 a 6", "1 a 5", "1 a 4", "1 a 3"],
    ["Qual pontuação de abertura ocular representa resposta a estímulo doloroso?", "2", "3", "1", "4"],
    ["Resposta verbal adequada, mas confusa, equivale a quantos pontos?", "4", "3", "2", "5"],
    ["A Escala de Glasgow é mais comumente usada em que ambiente?", "Emergência hospitalar", "Consultórios odontológicos", "Clínicas dermatológicas", "Salas de vacinação"],
    ["O que uma pontuação total de 15 indica na Escala de Coma de Glasgow?", "Estado de consciência normal", "Coma leve", "Confusão mental", "Desorientação"],
    ["Uma resposta verbal inapropriada recebe quantos pontos?", "3", "4", "2", "5"],
    ["Na resposta motora, qual a pontuação para obediência a comandos?", "6", "5", "4", "3"],
    ["Qual a principal vantagem da Escala de Coma de Glasgow?", "Padroniza a avaliação do nível de consciência", "Evita a necessidade de exames laboratoriais", "Substitui o eletroencefalograma", "Reduz o tempo de internação"],
    ["Qual pontuação indica necessidade imediata de intubação em muitos protocolos?", "Menor ou igual a 8", "Maior que 10", "Igual a 12", "Maior ou igual a 9"],
    ["Na Escala de Glasgow, qual é a faixa de pontuação total possível?", "3 a 15", "1 a 15", "0 a 10", "5 a 20"],
    ["Um paciente que apenas geme, sem formar palavras, recebe quantos pontos na resposta verbal?", "2", "1", "3", "4"],
    ["Qual das opções NÃO é um componente da Escala de Coma de Glasgow?", "Frequência respiratória", "Resposta ocular", "Resposta verbal", "Resposta motora"],
    ["A Escala de Glasgow foi criada em qual país?", "Escócia", "Estados Unidos", "Alemanha", "França"],
    ["Qual pontuação indica que o paciente responde apenas a estímulos dolorosos com extensão?", "2", "1", "3", "4"],
    ["A pontuação máxima para a resposta ocular é:", "4", "5", "6", "3"],
    ["Qual das alternativas representa uma pontuação compatível com coma severo?", "5", "12", "14", "10"],
    ["Quem criou a Escala de Coma de Glasgow?", "Graham Teasdale e Bryan Jennett", "Florence Nightingale", "Hans Berger", "Sigmund Freud"],
    ["Na resposta motora, extensão anormal ao estímulo doloroso indica qual pontuação?", "2", "3", "4", "5"],
    ["A Escala de Glasgow pode ser usada em crianças?", "Sim, com adaptações", "Não", "Apenas acima de 10 anos", "Apenas em adultos"],
    ["Uma resposta verbal confusa, mas com frases completas, equivale a:", "4", "5", "3", "2"],
    ["Um paciente com abertura ocular apenas à dor, fala incompreensível e extensão motora tem pontuação de:", "5", "6", "4", "7"],
    ["Em que ano a Escala de Coma de Glasgow foi publicada?", "1974", "1980", "1965", "1990"],
    ["Qual parâmetro da Escala de Glasgow possui maior variação de pontuação?", "Resposta motora", "Resposta verbal", "Resposta ocular", "Nenhum, todos são iguais"],
    ["Uma pessoa com fala orientada e resposta motora normal, mas sem abrir os olhos espontaneamente, teria que pontuação?", "14", "15", "13", "12"],
    ["Um paciente sem resposta ocular, verbal ou motora recebe qual pontuação?", "3", "0", "1", "2"],
    ["A Escala de Glasgow deve ser aplicada por:", "Profissionais de saúde treinados", "Familiares", "Psicólogos apenas", "Somente médicos"],
    ["A resposta motora 'retirada ao estímulo doloroso' equivale a:", "4", "5", "3", "2"],
    ["Fala sem sentido lógico, mas com palavras compreensíveis, pontua como:", "3", "2", "4", "5"],
    ["Um paciente abre os olhos ao comando e obedece ordens simples. Qual a pontuação mínima possível para essa condição?", "10", "12", "8", "15"],
    ["Um paciente que não fala, mas abre os olhos espontaneamente e retira o braço ao estímulo doloroso, pontua:", "10", "8", "11", "9"],
    ["O componente menos pontuado em pacientes com trauma craniano grave geralmente é:", "Resposta verbal", "Resposta ocular", "Resposta motora", "Todos pontuam igual"],
    ["Qual pontuação motora representa uma resposta localizando a dor?", "5", "6", "4", "3"],
    ["Um paciente que abre os olhos espontaneamente, fala orientado e obedece a comandos recebe:", "15", "12", "14", "13"],
    ["A Escala de Glasgow deve ser repetida periodicamente para:", "Avaliar a evolução neurológica do paciente", "Confirmar diagnóstico de diabetes", "Controlar pressão arterial", "Observar temperatura corporal"]

];

export default questoes;