const questoes = [
    ["Qual o primeiro passo no atendimento a uma vítima inconsciente?", "Verificar a responsividade", "Chamar o SAMU imediatamente", "Iniciar massagem cardíaca", "Colocar em posição lateral de segurança"],
    ["A manobra de Heimlich é utilizada em casos de:", "Engasgo com obstrução total", "Parada cardiorrespiratória", "Trauma craniano", "Fratura exposta"],
    ["Qual é a frequência recomendada de compressões torácicas na RCP em adultos?", "100 a 120 por minuto", "80 a 90 por minuto", "60 a 70 por minuto", "130 a 150 por minuto"],
    ["Em caso de queimadura química, deve-se:", "Lavar com água corrente por 20 minutos", "Aplicar pomada antibiótica imediatamente", "Cobrir com pano seco", "Estourar as bolhas formadas"],
    ["Quando suspeitar de lesão na coluna cervical?", "Em acidentes automobilísticos com impacto frontal", "Em cortes superficiais na perna", "Em pequenas escoriações no braço", "Em torções de tornozelo"],
    ["O que indica uma respiração agônica?", "Sinais de parada respiratória iminente", "Hiperventilação controlada", "Respiração normal após exercício", "Aspiração de líquidos"],
    ["No transporte de um politraumatizado, é correto:", "Imobilizar o pescoço com colar cervical", "Permitir que ele caminhe até a ambulância", "Levantar rapidamente para evitar hipotermia", "Dar água para acalmá-lo"],
    ["O sinal de Battle indica:", "Fratura na base do crânio", "Lesão no fígado", "Trauma na coluna lombar", "Fratura de fêmur"],
    ["Em hemorragias arteriais o sangue é caracterizado por:", "Fluxo pulsátil e vermelho vivo", "Fluxo lento e escuro", "Gotejamento contínuo", "Cor amarelada"],
    ["Qual posição é indicada para um paciente em choque hipovolêmico?", "Decúbito dorsal com elevação dos membros inferiores", "Sentado com tronco inclinado para frente", "Deitado de lado", "Em pé para melhorar circulação"],
    ["Na avaliação primária do trauma (ABCDE), o D refere-se a:", "Disability (estado neurológico)", "Desfibrilação", "Diagnóstico definitivo", "Desobstrução das vias aéreas"],
    ["Quando utilizar o desfibrilador externo automático (DEA)?", "Em paradas cardíacas por fibrilação ventricular", "Em intoxicação alimentar", "Em fraturas expostas", "Em casos de hipotermia leve"],
    ["Uma vítima que fala normalmente após acidente de carro provavelmente tem:", "Vias aéreas pérvias", "Fratura de mandíbula", "Obstrução parcial das vias aéreas", "Edema pulmonar"],
    ["O torniquete é indicado em casos de:", "Hemorragias massivas que não cessam com pressão direta", "Pequenos cortes superficiais", "Contusão muscular", "Epistaxe"],
    ["O que fazer em casos de convulsões?", "Proteger a cabeça e não conter movimentos", "Introduzir objeto na boca", "Dar água imediatamente", "Levantar rapidamente"],
    ["Em queimaduras elétricas deve-se:", "Avaliar entrada e saída da corrente", "Aplicar gelo no local", "Fazer massagem vigorosa", "Dar bebidas quentes"],
    ["O pulso carotídeo é verificado em:", "Adultos em parada cardiorrespiratória", "Bebês menores de 1 ano", "Pacientes com fratura de costela", "Casos de queimaduras de 2º grau"],
    ["A tríade letal no trauma é composta por:", "Hipotermia, acidose e coagulopatia", "Hiperglicemia, taquicardia e bradicardia", "Hiponatremia, hipocalemia e hipermagnesemia", "Cefaleia, náuseas e vômitos"],
    ["Em hemorragia nasal (epistaxe), deve-se:", "Compressão das narinas e inclinar a cabeça levemente para frente", "Deitar com cabeça para trás", "Tamponar com algodão seco", "Pedir para assoar o nariz forte"],
    ["No AVC hemorrágico, é comum encontrar:", "Déficit neurológico súbito e cefaleia intensa", "Sudorese fria e hipoglicemia", "Taquipneia leve e dor abdominal", "Edema de membros inferiores"],
    ["Em obstrução parcial das vias aéreas, o paciente geralmente:", "Tosse com esforço", "Fica imediatamente inconsciente", "Apresenta cianose generalizada", "Não consegue emitir nenhum som"],
    ["Qual o melhor local para injeção intramuscular em adultos em emergência?", "Região glútea ou vasto lateral", "Parte superior do braço", "Região do abdome", "Parte interna da coxa"],
    ["Em suspeita de fratura exposta, deve-se:", "Cobrir com compressa limpa e não tentar reduzir", "Colocar gelo diretamente", "Realizar movimentos para avaliar mobilidade", "Usar pomada anti-inflamatória"],
    ["Sinais de choque anafilático incluem:", "Edema facial, urticária e hipotensão", "Taquipneia, hiperglicemia e hiperreflexia", "Sudorese, hipertensão e dor torácica", "Mialgia, cefaleia e náusea leve"],
    ["Em parada cardiorrespiratória em lactentes, verifica-se o pulso em:", "Artéria braquial", "Artéria radial", "Artéria femoral", "Artéria carótida"],
    ["Um dos primeiros sinais clínicos de hipovolemia é:", "Taquicardia", "Bradipneia", "Hipertensão", "Rubor facial"],
    ["Para conter hemorragias externas, a primeira conduta é:", "Compressão direta do local", "Imobilizar o membro afetado", "Aplicar torniquete imediatamente", "Elevar o membro acima do nível do coração"],
    ["O score de Glasgow abaixo de 8 indica:", "Coma grave e necessidade de via aérea definitiva", "Estado ansioso moderado", "Dor torácica intensa", "Infecção respiratória alta"],
    ["Quando usar cânula orofaríngea?", "Em pacientes inconscientes sem reflexo de vômito", "Em pacientes conscientes com tosse", "Em vítimas de infarto agudo do miocárdio", "Em queimaduras extensas"],
    ["Após trauma, a verificação do enchimento capilar deve ser inferior a:", "2 segundos", "5 segundos", "8 segundos", "10 segundos"],
    ["O sinal de Guedel indica:", "Sangramento pelo ouvido após trauma craniano", "Presença de ar no subcutâneo", "Desvio de traqueia", "Edema de membros inferiores"],
    ["Qual a prioridade no atendimento inicial do politraumatizado?", "Manter vias aéreas pérvias", "Verificar temperatura", "Administrar analgesia", "Examinar fraturas"],
    ["Em intoxicação por produtos químicos ingeridos, é correto:", "Não provocar vômito e encaminhar para hospital", "Oferecer água em abundância", "Dar leite para neutralizar", "Fazer compressa quente no abdome"],
    ["O tamponamento cardíaco pode causar:", "Pulso paradoxal e turgência jugular", "Hipotermia e sudorese fria", "Hematêmese e icterícia", "Hipertermia e taquipneia"],
    ["Quando suspeitar de fratura de costela?", "Dor ao respirar e crepitação local", "Palidez e sudorese", "Edema em membros inferiores", "Hipertensão arterial súbita"],
    ["A síndrome compartimental ocorre quando:", "Há aumento da pressão dentro de um compartimento muscular", "Se forma um trombo arterial", "Há inflamação no tecido linfático", "Existe obstrução brônquica por secreção"],
    ["Na avaliação primária do trauma, o B refere-se a:", "Breathing (respiração)", "Blood pressure", "Bladder (bexiga)", "Body temperature"],
    ["Em queimaduras térmicas, o uso de pomadas deve ser feito:", "Apenas após avaliação hospitalar", "Imediatamente para aliviar a dor", "Junto com compressas geladas", "Com massagem local"],
    ["Em caso de amputação traumática de membro, o segmento deve ser:", "Envolto em pano limpo e colocado em saco plástico sobre gelo", "Imerso diretamente em água gelada", "Guardado seco em bolsa", "Colocado em solução salina morna"],
    ["A hipoglicemia grave pode levar a:", "Convulsões e perda de consciência", "Hipertensão e sudorese fria", "Edema pulmonar", "Bradicardia leve"],
    ["Em suspeita de pneumotórax hipertensivo, observa-se:", "Desvio de traqueia para o lado contralateral", "Elevação da pressão arterial", "Cianose de extremidades apenas", "Hematoma extenso no tórax"],
    ["Para avaliar resposta motora na escala de Glasgow, pergunta-se:", "Para o paciente obedecer comandos ou reagir à dor", "Se reconhece pessoas", "Quantos dedos está vendo", "Para mover a língua"],
    ["No afogamento, a prioridade é:", "Ventilação e oxigenação", "Aquecimento do corpo", "Imobilizar cervical", "Administrar fluidos intravenosos"],
    ["A tríade de Beck é típica de:", "Tamponamento cardíaco", "Choque séptico", "Infarto do miocárdio", "AVC isquêmico"],
    ["Sinais de obstrução total das vias aéreas incluem:", "Incapacidade de falar ou tossir", "Tosse com esforço", "Rouquidão leve", "Respiração ofegante"],
    ["Na imobilização de fratura de tíbia, deve-se incluir:", "As articulações acima e abaixo da lesão", "Somente a área lesionada", "Apenas a articulação inferior", "Compressas mornas"],
    ["Quando iniciar massagem cardíaca externa?", "Ausência de pulso carotídeo por 10 segundos", "Quando paciente relata dor torácica", "Em bradicardia moderada", "Após administrar oxigênio"],
    ["No trauma abdominal fechado, um sinal preocupante é:", "Rigidez abdominal", "Taquipneia isolada", "Sudorese palmar", "Leve desconforto local"],
    ["A escala de AVPU avalia:", "Nível de consciência", "Sinais vitais", "Gravidade da dor", "Perda de sangue"],
    ["A cianose central indica:", "Baixa oxigenação arterial", "Obstrução venosa superficial", "Hipotermia leve", "Hemorragia interna controlada"],
    ["O que fazer em picada de cobra venenosa?", "Manter o membro em repouso e abaixo do nível do coração", "Fazer torniquete apertado", "Cortar o local para sangrar", "Aplicar gelo diretamente"],
    ["O pulso radial geralmente é palpável em pressões sistólicas acima de:", "80 mmHg", "60 mmHg", "100 mmHg", "50 mmHg"],
    ["Em trauma torácico, presença de enfisema subcutâneo sugere:", "Lesão pulmonar com escape de ar", "Fratura de esterno", "Lesão hepática", "Contusão renal"],
    ["Um paciente com trauma cranioencefálico que abre os olhos ao som tem:", "3 pontos na abertura ocular pela Glasgow", "2 pontos", "4 pontos", "5 pontos"],
    ["O que é um pneumotórax aberto?", "Comunicação entre cavidade torácica e o meio externo", "Presença de ar no mediastino", "Inflamação pleural", "Acúmulo de líquido pleural"],
    ["Ao verificar enchimento capilar maior que 3 segundos, podemos suspeitar de:", "Hipoperfusão", "Infecção urinária", "Hipervolemia", "Hipertermia"],
    ["Em vítimas de trauma, deve-se evitar retirar o capacete quando:", "Há suspeita de lesão cervical", "A vítima estiver inconsciente", "Houver sangramento nasal", "O capacete estiver frouxo"],
    ["Um dos primeiros sinais clínicos do choque compensado é:", "Taquicardia", "Hipotensão imediata", "Bradipneia", "Hipertermia"],
    ["Em queimaduras de terceiro grau, observa-se:", "Pele esbranquiçada ou carbonizada, sem dor local", "Vesículas dolorosas", "Eritema com ardência", "Apenas rubor superficial"],
    ["A resposta pupilar lenta ou assimétrica após trauma indica:", "Pressão intracraniana elevada", "Desidratação", "Fratura de costela", "Choque hipovolêmico"],
    ["Em caso de fratura exposta, a primeira conduta é:", "Cobrir o ferimento com curativo estéril", "Reposicionar o osso imediatamente", "Aplicar gelo diretamente no osso", "Realizar massagem no local"],
    ["A obstrução parcial das vias aéreas geralmente apresenta:", "Tosse efetiva e sons respiratórios audíveis", "Ausência total de som respiratório", "Cianose imediata e perda de consciência", "Pupilas dilatadas"],
    ["O sinal de Battle indica:", "Fratura de base de crânio", "Trauma cervical", "Lesão de medula espinhal", "Pneumotórax hipertensivo"],
    ["A tríade clássica do choque inclui:", "Hipotensão, taquicardia e pele fria", "Hipertensão, bradicardia e rubor facial", "Hipotermia, bradicardia e sudorese", "Taquipneia, hipertensão e palidez"],
    ["Em um paciente queimado, suspeita-se de inalação de fumaça quando há:", "Rouquidão e fuligem em nariz e boca", "Dor localizada e vesículas", "Pele pálida e úmida", "Movimentos respiratórios normais"],
    ["O rebaixamento do nível de consciência pode indicar:", "Hipóxia cerebral", "Hiperglicemia controlada", "Boa perfusão tecidual", "Lesão ligamentar periférica"],
    ["No controle inicial de hemorragia externa, usa-se:", "Compressão direta no local", "Elevação do membro acima do coração sem compressão", "Aplicação imediata de torniquete sem avaliação", "Imobilização apenas com tala"],
    ["A manobra de Heimlich é indicada para:", "Obstrução total das vias aéreas em consciente", "Crise convulsiva generalizada", "Síncope vasovagal", "Choque anafilático"],
    ["Na avaliação da circulação em trauma, é fundamental checar:", "Pulso central e enchimento capilar", "Nível de glicemia capilar", "Movimentos voluntários", "Reflexos pupilares"],
    ["Em caso de contusão pulmonar, espera-se encontrar:", "Dispneia e estertores", "Rigidez abdominal", "Bradipneia sem esforço", "Edema periférico súbito"],
    ["No TCE, a presença de otorreia com líquido claro indica:", "Possível fratura de base de crânio com fístula liquórica", "Sangramento nasal simples", "Pressão intracraniana baixa", "Edema pulmonar"],
    ["O pulso paradoxal é característico de:", "Tamponamento cardíaco", "Choque neurogênico", "Hipotermia severa", "Insuficiência renal"],
    ["A classificação de queimaduras pelo grau depende:", "Da profundidade atingida", "Do tempo de exposição ao calor", "Da área corporal total apenas", "Da idade do paciente"],
    ["Na hipotermia moderada, é comum observar:", "Tremores intensos e confusão mental", "Hipertermia compensatória", "Rubor persistente", "Hiperglicemia leve"],
    ["A escala AVPU considera o paciente como A se:", "Está alerta e responde adequadamente", "Responde apenas à dor", "Tem resposta verbal confusa", "Está com respiração irregular"],
    ["No edema cerebral progressivo, pode ocorrer:", "Pupilas assimétricas e vômitos em jato", "Hiperatividade muscular", "Hipotensão isolada", "Sudorese fria localizada"],
    ["O choque séptico difere do hipovolêmico por:", "Vasodilatação periférica com extremidades quentes", "Pele fria e pegajosa", "Pulso filiforme", "Taquicardia compensatória"],
    ["Para calcular a superfície queimada utiliza-se:", "Regra dos nove de Wallace", "Índice de Glasgow", "Classificação de Frank-Starling", "Score de Wells"],
    ["A bradicardia sinusal em trauma craniano pode indicar:", "Aumento da pressão intracraniana", "Hipotermia leve", "Choque hipovolêmico inicial", "Perfuração gástrica"],
    ["Ao avaliar via aérea com coluna cervical suspeita, utiliza-se:", "Manobra de elevação do queixo com tração mandibular", "Hiperextensão do pescoço", "Flexão do pescoço sobre o tórax", "Compressão lateral do pescoço"],
    ["No trauma abdominal, o sinal de Cullen indica:", "Equimose periumbilical sugerindo sangramento interno", "Rigidez cervical", "Diminuição do murmúrio vesicular", "Hipertermia súbita"],
    ["Um paciente com pneumotórax hipertensivo apresenta:", "Hipertimpanismo à percussão", "Diminuição da frequência respiratória", "Hipovolemia inicial", "Bradipneia com tosse produtiva"],
    ["Quando realizar cricotireoidostomia?", "Obstrução alta das vias aéreas sem possibilidade de intubação", "Hipotensão arterial persistente", "Lesão fechada de tórax", "Fratura exposta de mandíbula"],
    ["A reposição volêmica inicial em trauma geralmente usa:", "Cristaloides aquecidos", "Albumina concentrada", "Plasma fresco congelado", "Solução hipertônica 7%"],
    ["Em suspeita de embolia pulmonar maciça:", "Dispneia súbita e dor torácica pleurítica", "Edema generalizado", "Rigidez abdominal", "Tremores finos nos dedos"],
    ["O sinal de Grey Turner corresponde a:", "Equimose em flancos, sugerindo sangramento retroperitoneal", "Pupilas desiguais", "Frequência respiratória aumentada", "Hipertensão arterial isolada"],
    ["A administração de O2 em máscara de alto fluxo é indicada em:", "Hipoxemia refratária", "Síncope vasovagal simples", "Dor abdominal difusa", "Edema de membros inferiores"],
    ["Na Glasgow, resposta verbal incoerente pontua:", "3 pontos", "2 pontos", "4 pontos", "5 pontos"],
    ["Ao encontrar vítima em parada cardiorrespiratória, deve-se:", "Iniciar RCP imediatamente", "Buscar primeiro sinais de fraturas", "Oferecer água e açúcar", "Posicionar em decúbito lateral"],
    ["O choque anafilático se caracteriza por:", "Vasodilatação sistêmica e broncoespasmo", "Aumento súbito da pressão arterial", "Hipotermia rápida", "Retenção urinária aguda"],
    ["Qual é a principal causa de choque hipovolêmico?", "Perda sanguínea aguda", "Infecção generalizada", "Falência cardíaca", "Obstrução pulmonar"],
    ["Na presença de suspeita de trauma cervical, o primeiro passo é:", "Imobilizar a coluna cervical", "Realizar elevação rápida do queixo", "Oferecer líquidos ao paciente", "Aplicar massagem cardíaca"],
    ["O sinal de Kussmaul caracteriza-se por:", "Aumento da jugular durante a inspiração", "Diminuição da frequência respiratória", "Movimentos respiratórios paradoxais", "Retração intercostal bilateral"],
    ["Quando se deve suspeitar de tamponamento cardíaco?", "Pulso paradoxal e turgência jugular", "Cianose periférica e bradicardia", "Sudorese fria e rubor facial", "Hipertermia e edema periférico"],
    ["No manejo inicial de um trauma torácico, deve-se priorizar:", "Avaliar permeabilidade das vias aéreas", "Realizar sondagem vesical imediata", "Iniciar analgesia forte", "Administrar anti-inflamatórios"],
    ["A presença de hematoma em asa do nariz pode indicar:", "Fratura de base do crânio", "Lesão pulmonar", "Fratura de mandíbula", "Edema de glote"],
    ["A tríade de Beck indica:", "Tamponamento cardíaco", "Embolia pulmonar", "Choque neurogênico", "Trombose venosa profunda"],
    ["Em caso de fratura pélvica, deve-se:", "Evitar movimentar o paciente desnecessariamente", "Realizar deambulação precoce", "Aplicar bolsa de gelo diretamente", "Elevar as pernas repetidamente"],
    ["No politrauma, qual exame tem prioridade após estabilização?", "FAST ultrassom", "Eletrocardiograma basal", "Exame oftalmológico", "Avaliação dental"],
    ["O sinal de Murphy é sugestivo de:", "Colecistite aguda", "Peritonite difusa", "Ruptura esplênica", "Infarto intestinal"],
    ["Na parada cardiorrespiratória em ambiente extra-hospitalar, recomenda-se:", "Compressões torácicas de alta qualidade", "Intubação imediata sem ventilação", "Administração de adrenalina subcutânea", "Verificar reflexos pupilares antes de iniciar"],
    ["A tríade clássica do AVC inclui:", "Paralisia facial, dificuldade de fala e hemiparesia", "Dor torácica, sudorese e palpitações", "Dispneia, taquicardia e cianose", "Dor abdominal, vômito e rigidez"],
    ["Na escala de Glasgow, abertura ocular ao estímulo doloroso pontua:", "2 pontos", "1 ponto", "3 pontos", "4 pontos"],
    ["Em caso de suspeita de pneumotórax aberto, faz-se:", "Cobertura do ferimento com curativo valvulado", "Compressão torácica manual", "Imobilização cervical estrita", "Infusão rápida de cristaloide"],
    ["Quando se observa sinal de Hamman?", "Enfisema mediastinal", "Hipertensão intracraniana", "Choque séptico", "Ruptura esplênica"],
    ["O crush syndrome está associado a:", "Lesões musculares extensas e liberação de mioglobina", "Lesão pulmonar unilateral", "Trauma cervical leve", "Isquemia miocárdica subendocárdica"],
    ["Em queimaduras elétricas, deve-se priorizar:", "Monitorização cardíaca contínua", "Aplicar pomada antibiótica imediatamente", "Manter posição de Trendelenburg", "Avaliar pressão intracraniana"],
    ["O sinal de Blumberg indica:", "Dor à descompressão brusca do abdômen", "Pulso rápido e fraco", "Hiperventilação compensatória", "Equimose periorbitária"],
    ["Na síndrome compartimental, o sintoma mais precoce é:", "Dor desproporcional ao exame", "Paralisia imediata", "Cianose distal", "Rigidez abdominal"],
    ["Para suspeitar de choque neurogênico, observa-se:", "Bradicardia e hipotensão", "Taquicardia e sudorese fria", "Pele úmida e fria", "Edema pulmonar difuso"],
    ["A hiperventilação pode ocorrer como resposta inicial a:", "Acidose metabólica", "Alcalose respiratória crônica", "Hipocalemia isolada", "Hipoglicemia moderada"],
    ["O sinal de McBurney sugere:", "Apendicite aguda", "Colelitíase sintomática", "Pancreatite hemorrágica", "Hérnia encarcerada"],
    ["Qual cuidado é imprescindível no atendimento do trauma cranioencefálico?", "Evitar elevação excessiva das pernas", "Administrar solução hipertônica sem critério", "Estímulo doloroso repetido para manter alerta", "Aplicar compressa gelada no pescoço"],
    ["Na avaliação ABCDE, o 'C' refere-se a:", "Circulação e controle de hemorragias", "Capacidade pulmonar residual", "Consciência e nível de alerta", "Controle glicêmico"],
    ["A ocorrência de dispneia súbita associada a estalido audível pode indicar:", "Pneumotórax espontâneo", "Infarto agudo do miocárdio", "Peritonite generalizada", "Embolia arterial periférica"],
    ["Qual o principal risco do transporte inadequado de vítima politraumatizada?", "Piora de lesões medulares", "Hipoglicemia de rebote", "Broncoespasmo reflexo", "Elevação abrupta da pressão arterial"],
    ["A hipernatremia aguda pode levar a:", "Desidratação celular cerebral", "Aumento da pressão venosa central", "Edema pulmonar cardiogênico", "Alcalose metabólica prolongada"],
    ["Quando se fala em 'triagem de desastre', o vermelho indica:", "Atendimento imediato por risco iminente de vida", "Caso leve, podendo aguardar", "Pacientes já óbito confirmados", "Alta prioridade social sem risco vital"],
    ["No trauma fechado de abdômen, suspeita-se de lesão esplênica ao observar:", "Dor referida no ombro esquerdo", "Rigidez cervical associada", "Dor lombar bilateral com radiação", "Disfagia progressiva"],
    ["Em parada cardíaca por FV, o tratamento inicial é:", "Desfibrilação elétrica", "Administração de bicarbonato", "Intubação e ventilação isolada", "Infusão lenta de soro fisiológico"],
    ["Em paciente com TCE grave, é contraindicado:", "Elevar a cabeça além de 30 graus", "Manter normocapnia", "Evitar hiperglicemia", "Controlar temperatura"],
    ["A escala de AVPU avalia:", "Nível de consciência", "Pressão venosa central", "Capacidade respiratória", "Função hepática"],
    ["Quando se observa crepitação subcutânea, pensa-se em:", "Enfisema subcutâneo", "Peritonite química", "Isquemia intestinal", "Trombose venosa profunda"],
    ["No choque anafilático, o tratamento imediato é:", "Adrenalina intramuscular", "Hidrocortisona endovenosa inicial", "Dobutamina em bolus rápido", "Bicarbonato intravenoso"],
    ["A principal prioridade no manejo do politraumatizado é:", "Assegurar via aérea", "Fazer exames complementares", "Iniciar antibioticoterapia", "Reposição eletrolítica"],
    ["Em casos de afogamento, deve-se priorizar:", "Ventilação com oxigênio suplementar", "Administração imediata de diurético", "Realizar compressão abdominal", "Aplicar calor excessivo"],
    ["O sinal de Cullen indica:", "Hemorragia retroperitoneal", "Pneumotórax hipertensivo", "Edema pulmonar agudo", "Necrose hepática difusa"],
    ["Em parada cardíaca, a administração de adrenalina faz-se a cada:", "3-5 minutos", "10-15 minutos", "2-3 minutos", "7-8 minutos"],
    ["Qual característica sugere choque séptico e não hipovolêmico?", "Pele quente e avermelhada inicialmente", "Hipotensão com extremidades frias", "Sudorese intensa e palidez", "Pulso filiforme"],
    ["No pneumotórax hipertensivo, observa-se:", "Desvio da traqueia para o lado contralateral", "Hiperventilação bilateral", "Ausculta pulmonar sem alterações", "Bradipneia com sons abolidos bilateralmente"],
    ["Na escala de Glasgow, ausência de resposta motora pontua:", "1 ponto", "2 pontos", "3 pontos", "4 pontos"],
    ["O sinal de Gray-Turner é evidenciado por:", "Equimose em flancos", "Crepitação cervical", "Rigidez muscular difusa", "Movimento respiratório paradoxo"],
    ["Em trauma craniano, qual alteração pupilar indica pior prognóstico?", "Midríase unilateral fixa", "Miose bilateral reativa", "Anisocoria leve reativa", "Midríase bilateral fotorreagente"],
    ["A tríade clássica do tamponamento cardíaco é:", "Hipotensão, turgência jugular e bulhas abafadas", "Hipertensão, taquicardia e pulso largo", "Cianose central, dispneia e edema", "Taquipneia, rubor e sudorese fria"],
    ["O objetivo da ressuscitação volêmica inicial em choque hipovolêmico é:", "Restabelecer perfusão tecidual", "Aumentar temperatura corporal", "Reduzir pressão intracraniana", "Corrigir alcalose respiratória"],
    ["Qual conduta imediata no paciente inconsciente sem pulso?", "Iniciar compressões torácicas", "Aplicar O2 por máscara facial", "Elevar membros inferiores", "Administrar solução hipertônica"],
    ["No trauma abdominal, irritação peritoneal é indicada por:", "Dor à descompressão brusca", "Hiperemia conjuntival", "Rigidez cervical", "Hipertensão arterial súbita"],
    ["Em caso de fratura exposta, faz-se primeiro:", "Cobrir com curativo estéril e evitar manipular", "Realizar sutura primária imediata", "Imobilizar com tala gessada fechada", "Iniciar anticoagulação profilática"],
    ["No edema agudo de pulmão cardiogênico, o tratamento imediato inclui:", "Diurético intravenoso e vasodilatador", "Reposição rápida de soro fisiológico", "Dobutamina em alta dose inicial", "Ventilação com PEEP baixa obrigatória"],
    ["O pulso paradoxal é característico de:", "Tamponamento cardíaco", "Choque neurogênico", "Infarto de parede inferior", "Sepse grave com vasodilatação"],
    ["Paciente com trauma torácico fechado e hipersonoridade à percussão sugere:", "Pneumotórax", "Hemotórax", "Contusão pulmonar", "Derrame pleural"],
    ["Quando utilizar solução hipertônica em emergência?", "Na hipertensão intracraniana", "No choque distributivo inicial", "Na acidose metabólica leve", "Na intoxicação por organofosforado"],
    ["Em intoxicação por monóxido de carbono, a prioridade é:", "Oxigenoterapia 100%", "Administração de bicarbonato", "Diálise imediata", "Uso de adrenalina endovenosa"],
    ["O sinal de Battle indica:", "Fratura de base do crânio", "Isquemia mesentérica", "Necrose pancreática", "Derrame pleural maciço"],
    ["A bradicardia acompanhada de hipotensão após lesão medular sugere:", "Choque neurogênico", "Choque hipovolêmico", "Choque obstrutivo", "Choque séptico inicial"],
    ["O sinal de Hoover indica:", "Movimento paradoxal no EAP grave", "Dor abdominal irradiando para escápula", "Desvio da traqueia", "Isquemia miocárdica silenciosa"],
    ["Em paciente com fratura costal múltipla e dor intensa, deve-se:", "Controlar dor para permitir ventilação eficaz", "Aplicar tala rígida para limitar movimento", "Incentivar tosse constante", "Administrar alta dose de antiemético"],
    ["Na triagem em incidente com múltiplas vítimas, preto indica:", "Paciente sem possibilidade de salvamento", "Atendimento imediato", "Observação prolongada", "Alta prioridade hospitalar sem urgência"],
    ["A hipotermia acidental grave pode evoluir com:", "Arritmias ventriculares", "Hipertermia compensatória", "Pupilas puntiformes reativas", "Taquipneia prolongada"],
    ["Sopro sistólico novo após trauma torácico pode indicar:", "Lesão valvar", "Contusão hepática", "Tamponamento pericárdico", "Pneumotórax hipertensivo"]
];

export default questoes;